### ISSUE TITLE
Track OmniSharp versions for compatibility

### ISSUE THREAD

**Issue by sp3ctum** [OmniSharp/omnisharp-emacs#13]
This ticket mainly concerns OmniSharp development.

Newly developed features sometimes consist of changes to two projects:
- OmniSharp, which omnisharp-emacs depends on
- omnisharp-emacs itself

For a version of omnisharp-emacs to be valid it needs a specific
version of the OmniSharp backend - otherwise something might be broken.
For this reason it's beneficial to track OmniSharp versions along with
omnisharp-emacs versions.

This can be done by adding a git submodule in the repository root,
much like in the Vim binding here: https://github.com/nosami/Omnisharp .
Users / developers will not be forced to use the reference, but they
can use it to confirm they have the necessary version.

It will also help with installation. The typical user will want to
install the whole deal - since omnisharp-emacs is useless as a
frontend without the OmniSharp backend.

**Comment by razzmatazz** [comment]
I think we have this resolved this with the new `M-x omnisharp-install-server` command which will use `(defcustom omnisharp-expected-server-version ...)`

Closing
