### ISSUE TITLE
omnisharp-emacs fails to build under windows

### ISSUE THREAD

**Issue by laughingboy** [OmniSharp/omnisharp-emacs#131]
After having this problem with emacs 24.3.1, I upgraded to the latest emacs for windows (24.4) and still had the issue.

GNU Emacs 24.4.1 (i686-pc-mingw32)  of 2014-10-24 on LEG570

I started with a fresh install of emacs and a home directory containing nothing but a pared down .emacs file with only melpa support as follows:

``` lisp
(require 'package)
;; (add-to-list 'package-archives
;;             '("melpa-stable" . "http://stable.melpa.org/packages/") t)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)
```

Note that from this fresh state an install from melpa-stable fails since csharp-mode version 0.8.6 cannot be found; one must use the melpa repo instead.

Doing a package-install of omnisharp then fails on compiling omnisharp.el as follows:

omnisharp.el:330:1:Error: Invalid function: --mapcat

Line 330 is the start of the definition for the omnisharp-find-usages-worker function:
(defun omnisharp-find-usages-worker (request callback)

The final message output from the build process is:
Done (Total of 4 files compiled, 1 failed, 2 skipped)

**Comment by razzmatazz** [comment]
Closing as it is related to a legacy branch.
Please reopen if this is still a problem with the latest version.
