### ISSUE TITLE
Tabs!

### ISSUE THREAD

**Issue by nosami** [OmniSharp/omnisharp-emacs#141]
Autocomplete and possibly other endpoints don't work if there are any tab characters on the line.

**Comment by razzmatazz** [comment]
@nosami – do you remember more details on this?

I have not encountered this lately (or never, probably, for 1,5 years with omnisharp-emacs/roslyn)

**Comment by sp3ctum** [comment]
Maybe this is a good case for writing a test. Say "find type" with a tab
character on the line. Or just try out by hand.

My hunch is that it is not a problem any longer, but cannot remember
accurately.

**Comment by razzmatazz** [comment]
Seems to be working ok (did a manual test)
