### ISSUE TITLE
load-path resolution broken

### ISSUE THREAD

**Issue by ilohmar** [OmniSharp/omnisharp-emacs#144]
Hi there,

trying omnisharp-emacs seriously for the first time, to move further away from VS, and I like it!

With the recent source file split, however, the load-path needs additional directories (for a non-package install like a git clone).  It seems `omnisharp.el` is trying to do that with

``` elisp
(add-to-list 'load-path (expand-file-name "./src/"))
(add-to-list 'load-path (expand-file-name "./src/actions/"))
```

right at the top, but this does not work (at least for me) since the current directory could be anything at the time of expansion --- so I end up adding not one, but three entries myself.

Now this could surely be fixed, but I will ask very bluntly here: Is there a good reason for spreading the elisp files over 3 directory levels?  Usually Emacs packages put their various `.el` files into the same directory for good reason (load-path, navigation, moving dirs around..).  The shell scripts, on the other hand, I would not mind demoting to a sub-directory...

I hope this does not come across as a bike-shedding attempt.

**Comment by sp3ctum** [comment]
@ilohmar please check if this works now, I merged @robewald 's patch

**Comment by ilohmar** [comment]
Works!  I have to re-iterate, however, that I think this is a problematic (changing the global `load-path`...) way to work around just putting the files into the top dir.  If you are set on keeping it that way, a better method would be to directly use the constructed path in `(require 'omnisharp-utils "path/to/filename.el")`.

**Comment by razzmatazz** [comment]
@sp3ctum – what do you think if i move every *.el file that gets shipped to the root directory..

As far as I see all the packages use the schema where all .el files resides on the root/main directory and they do no load-path modifications themselves..

Exhibit #1: https://github.com/emacs-evil/evil/
Exhibit #2: https://github.com/emacs-helm/helm

**Comment by sp3ctum** [comment]
I think it's a really good idea. I didn't anticipate this use case when I wanted to organize code into multiple files back then..

Some test files mimic the directory structure. Since after this change the directory structure will vanish, I guess you could place all test files in a common directory as well.

**Comment by razzmatazz** [comment]
closing as the code has been moved as of #282
