### ISSUE TITLE
"Symbol's function definition is void: flycheck-set-checker-properties" on boot

### ISSUE THREAD

**Issue by tenpn** [OmniSharp/omnisharp-emacs#155]
I upgraded all my packages (this is always a mistake!) and now I get this error on boot. 

Booting with debug gives this callstack: 

    debugger entered--Lisp error: (void-function flycheck-set-checker-properties)                
      flycheck-set-checker-properties(csharp-omnisharp-curl ((flycheck-documentation . "A csharp$
      byte-code("^H^Q\302\301\303\304\305DD\306\307\310\311\312\313\314&    \210\315\301!\210\31$
      #<subr require>(omnisharp nil nil)                                                         
      ad-Advice-require(#<subr require> omnisharp)                                               
      apply(ad-Advice-require #<subr require> omnisharp)                                         
      require(omnisharp)                                                                         
      eval-buffer(#<buffer  *load*> nil "/Users/Andrew/.emacs.d/init.el" nil t)  ; Reading at bu$
      load-with-code-conversion("/Users/Andrew/.emacs.d/init.el" "/Users/Andrew/.emacs.d/init.el$
      load("/Users/Andrew/.emacs.d/init" t t)                                                    
      #[0 "^H\205\262^@ \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\$
      command-line()                                                                             
      normal-top-level()                                                                         
                          
I have omni version 20150107.850 and flycheck 20150307.728 from melpa. In my init.el I require omnisharp after flycheck. Any other information I can give you?

**Comment by sp3ctum** [comment]
To be hones this might be a mess to recover from. Could you try it on a new emacs instance and see if the error persists?

**Comment by tenpn** [comment]
Since I posted this, I re-did my whole config based on Prelude, and made sure to update my omnisharp server. Now things are working fine!
