### ISSUE TITLE
I am getting "listp 69", when I am trying to set up autocompletion

### ISSUE THREAD

**Issue by Armoken** [OmniSharp/omnisharp-emacs#157]
Hello, I am on ubuntu 14.10, emacs 24.3.1

I installed all required packages and added the following lines to .emacs. 

(add-to-list 'load-path "~/.emacs.d/elpa/omnisharp-20150107.850")
(require 'omnisharp-utils)
(add-to-list 'load-path "~/.emacs.d/elpa/omnisharp-20150107.850")
(require 'omnisharp-server-actions)
(add-to-list 'load-path "~/.emacs.d/elpa/omnisharp-20150107.850")
(require 'omnisharp-auto-complete-actions)
(setq omnisharp-start-omnisharp-server t)
(add-hook 'csharp-mode-hook 'omnisharp-mode)
(eval-after-load 'company
    '(add-to-list 'company-backends 'company-omnisharp))

I can start emacs normally, but when I am writing something I am getting 
Company: Back-end company-omnisharp error "Wrong type argument: listp, 69" with args (candidates usi)

**Comment by sp3ctum** [comment]
Sounds like your setup is weird. Please try reinstalling the recommended way (via MELPA) with a blank emacs. You can get a blank emacs by doing
`HOME=/tmp/lol/ emacs`

**Comment by Armoken** [comment]
So,  thanks, I reinstalled OmniSharp. And all everething worked. But there is one little problem. All it working only if I manually running OmniSharpServer. How to run it automatically? I added 
(setq omnisharp-server-executable-path ":~/.emacs.d/OmniSharpServer/OmniSharp/bin/Debug/OmniSharp.exe").
But it doesn't start automatically. If trying to start OmniSharpServer for solution file, I am getting

error in process sentinel: omnisharp--server-process-sentinel: OmniSharp server process exited abnormally with code 2

**Comment by sp3ctum** [comment]
Does it work without the colon? (:)

**Comment by Armoken** [comment]
Yes, its working)

**Comment by sp3ctum** [comment]
Awesome!
29.3.2015 22.50 kirjoitti "Armoken" <notifications@github.com>:
