### ISSUE TITLE
[Windows 7] No output in *Omni-Server* buffer

### ISSUE THREAD

**Issue by syl20bnr** [OmniSharp/omnisharp-emacs#159]
I compiled the OmniSharp server and OmniSharp.exe automatically launch it with the correct `.sln`. But for some reason there is no output in `*Omni-Server*` buffer and `omnisharp-check-alive-status` output is `not alive`. When I quit emacs the process is still running and I have to kill it.
I have curl installed and visible from within Emacs.
Another data point, I don't seem able to make other processes like `pt` or `ack` work properly too (i.e. no output).

Seems to be a communication issue between the child process and Emacs.

Do you have any hint about where to look at ?

**Comment by syl20bnr** [comment]
This is non blocking issue for me, I fixed my issue with #160 
I let you judge if this issue should be closed.

**Comment by sp3ctum** [comment]
Great that you got it fixed! :)
