### ISSUE TITLE
Cannot install from the MELPA repository

### ISSUE THREAD

**Issue by tearvisus** [OmniSharp/omnisharp-emacs#162]
When I try to install OmniSharp with the package-install command from the 'melpa-stable' archive I get the following message:
> Need package `dash-20141201.2206', but only 2.10.0 is available.

Here's my init.el file:

    (require 'package)
    (add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))
    (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
    (add-to-list 'package-archives '("marmalade" . "https://marmalade-repo.org/packages/"))
    (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
    (package-initialize)

I've tried this with both Emacs 24 and 25.

**Comment by sp3ctum** [comment]
The melpa stable is somewhat messed up right now. Try installing with just melpa (not stable). That's what the integration tests use, so it should work.
