### ISSUE TITLE
Emacs hangs on OSX if you try to open a C# file with dos line endings

### ISSUE THREAD

**Issue by tenpn** [OmniSharp/omnisharp-emacs#164]
Via a git repo, I had a C# file with dos line endings. When I tried to open it, emacs froze completely and I hate to force-kill it. This happened a few times in a row. I was able to open the file if I disabled omnisharp. After I ran dos2unix on the file, emacs+omnisharp would open it again. 

I have OSX 10.10.2, running emacs 24.5.1 installed via brew. I have the latest omnisharp server from github and omnisharp plugin 20150107.850. 

(Unfortunately I don't know how to grab a callstack from a frozen emacs. Is that possible?)

**Comment by sp3ctum** [comment]
Hi, sounds interesting. Could you run the server with -v Verbose and see what is being logged? Post it here too, please.

If emacs hangs it's probably an emacs side issue (just a guess)

**Comment by razzmatazz** [comment]
Seems to be working for me (no crash on macos sierra). Please reopen if this is still a problem.
