### ISSUE TITLE
Melpha OmniSharp install

### ISSUE THREAD

**Issue by Morvalyn** [OmniSharp/omnisharp-emacs#167]
Cannot install Omnisharp seems like it's looking for an old dash package.

"Need package `dash-20141201.2206', but only 2.10.0 is available.

Please let me know if this gets resolved, it's somewhat of a hindrance.

**Comment by sp3ctum** [comment]
Maybe you're installing from MELPA stable. Try installing from MELPA
(not stable) instead. The build server installs the package from
there, and it works.

The packages omnisharp-emacs depends on might have some kind of
version conflict. I think we need to drop support for MELPA stable
altogether if these continue.

**Comment by sp3ctum** [comment]
Please comment in #162
