### ISSUE TITLE
Wait for server startup

### ISSUE THREAD

**Issue by juergenhoetzel** [OmniSharp/omnisharp-emacs#169]
Requests to the OmniSharp Server are sent, even if the server isn't alreadly listening on Port 2000.

For example, if you enable flycheck via 

```
(add-hook 'omnisharp-mode-hook 'flycheck-mode)
```

you will most likely get this error

```
2015-05-04T22:10:58+0200
omnisharp--json-read-from-string error: ""
```

because the connection on Port 2000 is refused while the server is still starting.

**Comment by d12frosted** [comment]
Also interested in it.

**Comment by d12frosted** [comment]
Or even more - when I don't wait for server to startup and something sends a request to server - I am getting stuck. So I need to press `C-g` several times until I see `Quit` and emacs is unstuck.

**Comment by razzmatazz** [comment]
I think we have it working nowadays with roslyn and the new omnisharp-emacs release.
