### ISSUE TITLE
Syntax highlighting for #if blocks

### ISSUE THREAD

**Issue by d12frosted** [OmniSharp/omnisharp-emacs#173]
Hey,

On the project I am currently working on people are using symbols for conditional compiling very heavily. I am talking about symbols like `DEBUG`, `RELEASE` or whatever else you want.

```csharp
#if SYMBOL
    // code for SYMBOL only
#else
    // code for all other cases
#endif
```

`csharp-mode` knows nothing about those symbols, so it just highlights syntax in both cases. In Visual Studio it shows you the branch that will not compile as a comment. And it comes very useful sometimes. 

So my request is to implement the same behaviour of syntax highlighting. I understand, that `omnisharp-emacs` is a not about highlighting, but it has (using omnisharp server) knowledge about symbols. That's why I thought that this is a good place for such feature request. But in case it's not - my apologises.

**Comment by d12frosted** [comment]
Actually, I understand that this is very minor thing (I bet you have much more interesting things to do). That's why I could try to make this. But I'll need some help :D

**Comment by nosami** [comment]
omnisharp-server doesn't have a highlighting api yet.. but omnisharp-roslyn just got a PR for this exact feature (https://github.com/OmniSharp/omnisharp-roslyn/pull/194).

We're going to try and get this api into Atom soon... but the PR isn't going to get merged unless someone manages to use it :)

OmniSharp doesn't yet have a way to specify which is the active #ifdefs

**Comment by d12frosted** [comment]
> OmniSharp doesn't yet have a way to specify which are the active #ifdefs

Ah, that's answers the question I got recently, when I couldn't find the way to check the status of symbol.

> but omnisharp-roslyn just got a PR for this exact feature

That's neat. Sorry, @nosami I installed roslyn version, but haven't tried it yet!

**Comment by sp3ctum** [comment]
Closing due to this being pretty old. Please reopen if you want.
