### ISSUE TITLE
Change formatting of constructor/method arguments

### ISSUE THREAD

**Issue by kostrse** [OmniSharp/omnisharp-emacs#199]
Omnisharp mode aggressively tries to format my constructor / method like this:

``` c#
var longVariableName = new SomeClassWithVeryLongLongLongName(
                                                             new Prop("a", 1),
                                                             new Prop("b", 2),
                                                             new Prop("c", 3)
);
```

But I want only 4 spaces:

``` c#
var longVariableName = new SomeClassWithVeryLongLongLongName(
    new Prop("a", 1),
    new Prop("b", 2),
    new Prop("c", 3)
);
```

How can I configure/change this? Thanks!

**Comment by nosami** [comment]
Indentation is controlled by [csharp-mode](https://github.com/josteink/csharp-mode). You should ask over there. Thanks!

**Comment by razzmatazz** [comment]
@kostrse 

`csharp-mode` uses `cc-mode` under the hood, so you may want to `setq c-set-style` to some kind of value. e.g.:

```
    (setq c-syntactic-indentation t)
    (c-set-style "ellemtel")
```

I will add some documentation to README.md for this..
