### ISSUE TITLE
trying to type 'yield return new WaitForSeconds' automatically crashes emacs when company-mode is enabled

### ISSUE THREAD

**Issue by cc-lam** [OmniSharp/omnisharp-emacs#200]
Not sure if this is a bug with omnisharp or company-mode.

Using Spacemacs 0.104.2 with company-mode enabled, Emacs automatically crashes after I've typed `yield return new Wa` 

emacs does not crash if company-mode is disabled or if I insert the code with a snippet.

**Comment by razzmatazz** [comment]
@cc-lam sorry for writing this late, but is this still a problem for you?

We have released a completely revamped version of omnisharp-emacs which fix your problems

I am closing it because the issue is rather old — please reopen if this is a problem for you.
