### ISSUE TITLE
Search for projects by searching the project.json file, in addition to .sln files.

### ISSUE THREAD

**Issue by dgalizzi** [OmniSharp/omnisharp-emacs#206]
Currently I need to manually run the server if I don't have a solution file. Maybe https://github.com/OmniSharp/omnisharp-emacs/blob/master/src/actions/omnisharp-server-actions.el#L7 should look for project.json files and start folder mode if it doesn't find any sln files ?

In ASP.NET 5 solutions are no longer required, when developing without visual studio we don't use a solution, instead the project.json file is used to define project-specific information (in fact, you can open a project in visual studio by selecting a project.json file and it will create a solution for you).

**Comment by sp3ctum** [comment]
This sounds like stuff for omnisharp-roslyn, the new backend.
Omnisharp-emacs doesn't have full support for omnisharp-roslyn yet. There
is a branch that is working toward that goal here. Most features work for
me and other developers, but I don't know if it's production ready.
... meaning I haven't tried it on a real solution in a real scenario.

Are you using the old or new server? If you're using the new one this may
be an easy fix to master like you propose, and it can be ported to the
omnishar-roslyn support branch too.

2015-12-02 21:19 GMT+02:00 Diego D. Galizzi <notifications@github.com>:

**Comment by dgalizzi** [comment]
I'm currently using omnisharp-roslyn but with the master branch on omnisharp-emacs. I'll hack a bit and see if I can get this done.

**Comment by razzmatazz** [comment]
@dgalizzi 

sorry for getting to you this late;

project.json experiment is on the way out – see https://www.infoq.com/news/2016/05/project-json – and with our limited resources we are not going to add support for this..
