### ISSUE TITLE
company does not show parameters and return values (MAC OS 10.11)

### ISSUE THREAD

**Issue by sandao** [OmniSharp/omnisharp-emacs#208]
<img width="592" alt="screen shot 2015-12-09 at 1 07 52 pm" src="https://cloud.githubusercontent.com/assets/7250358/11677200/f12d737c-9e75-11e5-867e-5867614c1f8e.png">

**Comment by sp3ctum** [comment]
How can I reproduce this?

2015-12-09 7:08 GMT+02:00 sandao <notifications@github.com>:

**Comment by sandao** [comment]
Sorry, this may be my own fault

**Comment by sp3ctum** [comment]
Okay, cool :)

2015-12-09 15:06 GMT+02:00 sandao <notifications@github.com>:
