### ISSUE TITLE
not show correct documentation in the the company-mode popup

### ISSUE THREAD

**Issue by sandao** [OmniSharp/omnisharp-emacs#210]
in my emacs, not show correct documentation in the the company-mode popup, only method name!
![screen shot 2016-04-04 at 1 53 52 am](https://cloud.githubusercontent.com/assets/7250358/14234003/8e36ac5c-fa0a-11e5-98dc-8d367a09caf1.jpg)

**Comment by razzmatazz** [comment]
Not sure we can fix this is company-mode itself does not allow for documentation to be shown along side with completion item. I will check.

**Comment by razzmatazz** [comment]
Yes, we can do this with `meta` and `annotation` implementation on company backend.
An example to follow is:
 - https://github.com/company-mode/company-mode/blob/c494fc65d35f7f00c2da17206e6550385ae9b300/company-clang.el#L322

**Comment by razzmatazz** [comment]
Actually, hitting F1 while in company mode popup shows me documentation alright.
It could be that you were using the non-roslyn omnisharp-emacs/server and it wasn't working at the time but it does work now for me.

Please reopen if this is still valid for you.
