### ISSUE TITLE
omnisharp-pkg.el 

### ISSUE THREAD

**Issue by xianghx** [OmniSharp/omnisharp-emacs#212]
I use company-mode, why I need to install   (auto-complete "1.4") 
?

**Comment by jtbm37** [comment]
`omnisharp-emacs` tried to provide completion for as many autocompletion packages as there was out there.

We should probably try to separate them into their own package (eg `omnisharp-auto-complete`, `omnisharp-company`) and somehow autoload them.

I am not sure what other packages do whenever they tried to be completion agnostic.
