### ISSUE TITLE
Add http request to roslyn branch

### ISSUE THREAD

**Issue by jtbm37** [OmniSharp/omnisharp-emacs#216]
Any reason this was dropped or were you just trying to assess if the IO version was viable ?

**Comment by jtbm37** [comment]
A situation were http request is applicable is when the omnisharp server is not on the same machine as the emacs client.

**Comment by sp3ctum** [comment]
Ah good point. The io was preferred to keep the majority of use cases simple. The scenario you describe is viable, and I've even tried it myself.

In other words, I see no reason not to include an HTTP request option too. For the time being I'll probably focus on stabilizing the io method.

I'm trying to pick up development again, and first trying to get the tests passing on the incremental-updates branch. When that happens, I think the tests could even be ran with both transport options.

**Comment by jtbm37** [comment]
While trying to optimize the http request parsing I got some really good results.

This is when trying to pull all symbols (2897) from the `omnisharp-roslyn` project.

BEFORE
```
ELISP> (benchmark-run (omnisharp-post-message-curl "findsymbols" '((Filter . ""))))
(2.614968005 0 0.0)
```

AFTER
```
(benchmark-run (omnisharp-post-message-curl "findsymbols" '((Filter . ""))))
(0.27627309 0 0.0)
```
Now listing all those symbols in helm is pretty smooth.

**Comment by sp3ctum** [comment]
Hey that looks very nice! How did you do it?
And please tell me when we can merge it in :smile:

**Comment by jtbm37** [comment]
@sp3ctum using [request](https://github.com/tkf/emacs-request)

**Comment by jtbm37** [comment]
PR #223

**Comment by sp3ctum** [comment]
Closing as the PR was merged.
