### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by awb99** [OmniSharp/omnisharp-emacs#217]
I am struggling to run this. Is there anywhere a list of steps that need to be done so that I can use EMacs with OmniSharp? 

THANKS!!

**Comment by jtbm37** [comment]
@awb99 have you read the installation section on the readme (front-page) ?

**Comment by sp3ctum** [comment]
If you have problems, ask away! Also mention what platform you're on :+1:

**Comment by awb99** [comment]
Hi Gents! 

I have read the readme page. 

Do I have to install omnisharp and then omnisharp-emacs via "MELPA"?

I run debian 8 and and also arch.

I have to admit that I am also a emacs novice; I want to switch from windows 7 with SharpDevelop to leaner emacs/omnisharp system

**Comment by sp3ctum** [comment]
Welcome to the tribe :smiley: 

I use linux mint at home myself, here's what you need to do:
- install OmnisharpServer (not omnisharp-roslyn)
- install curl
- install omnisharp-emacs via MELPA

If you are a novice, I recommend spacemacs which I switched to a couple of weeks ago personally.

**Comment by sp3ctum** [comment]
omnisharp-roslyn is under development, and it apparently works for some people. But it might have rough edges! :)

**Comment by awb99** [comment]
Thanks! 

 Omnisharp server and curl are easy. 

I got spacemacs settings downloaded..  Seems to be  keyboarding to Emacs. 

But Melpa I don't get it.  I guess I have to do this settings within Emacs?

**Comment by jtbm37** [comment]
@awb99  Once you've got spacemacs set up, you just have to enable the `csharp` layer in your `.spacemacs` file like [this](https://github.com/jtbm37/dotfiles/blob/master/emacs/spacemacs.symlink#L44) and then restart emacs. 

Spacemacs has what it calls "layers". It is its own invention which has nothing to do with Emacs. It allows you to pre-initialize a set of modes and pull all the necessary packages from melpa/elpa for you.

The [csharp](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/csharp) layer initializes the `csharp-mode` and `omnisharp-mode`.

Have a look at all the [layers](https://github.com/syl20bnr/spacemacs/tree/master/layers) available. Each of them should have a readme and tell you how to install it. It is generally just a case of putting a name in the `dotspacemacs-configuration-layers` list. 

If you wish to install manually other packages from elpa/melpa it is just `M-x package-install` away !

**Comment by sp3ctum** [comment]
Closing for now, pls re-open if you still have questions.

**Comment by awb99** [comment]
@sp3ctum thanks for your help! I now managed to install omnisharp. Even though all steps are not rocket science, I dont find it easy to get started. I am offering to write a tutorial to explain how to do install it. I can do this in a couple of months, once I somehow am running myself.

**Comment by sp3ctum** [comment]
Glad to hear you got it running!

I agree: getting started is really painful at the moment. Any tutorial
about this would be great. If you have the time to make one, I'll be glad
to include it.

2016-04-29 13:36 GMT+03:00 awb99 <notifications@github.com>:

**Comment by awb99** [comment]
@sp3ctum I added a how to install it wiki page.
