### ISSUE TITLE
using omnisharp-emacs

### ISSUE THREAD

**Issue by awb99** [OmniSharp/omnisharp-emacs#220]
How do I solve this error message after starting the Omnisharp-Emacs plugin?

```
Could not find the OmniSharpServer.
 Please set the variable omnisharp-server-executable-path to a valid path.
```

**Comment by jtbm37** [comment]
`(setq omnisharp-server-executable-path "/path/to/omnisharp/server")` in your `init.el`.

**Comment by awb99** [comment]
thanks!  
I now managed to get spacemacs installed with emacs key bindings.
I try to understand what the SPC key is...  It seems that the normal C- or M- bindings work;
but in the help file it always talks about SPC..No idea where this key is.

**Comment by jtbm37** [comment]
@awb99  `SPC` is the space bar. ;) All keybindings start with the space bar, hence Spacemacs (Space + Emacs).

**Comment by awb99** [comment]
@jtbm37  they say SPC f s      saves the current buffer.  When I enter space f s then
all I see is fs. How would spacemac know that space should not be interpreted as a space?

**Comment by awb99** [comment]
@jtbm37 I think I got it. When spacemacs runs in emacskeybinding mode,then SPC is ALT M.

**Comment by jtbm37** [comment]
@awb99 That's right.

**Comment by awb99** [comment]
@jtbm37 1000 thanks! This was a simple issue; but nevertheless I didnt quite figure it out.. hahah

**Comment by jtbm37** [comment]
@awb99 You're welcome.
