### ISSUE TITLE
[Roslyn] Improve symbol request performance

### ISSUE THREAD

**Issue by jtbm37** [OmniSharp/omnisharp-emacs#225]
On a fairly large project with more than 60k symbols it takes between 4 to 6 seconds to retrieve all of them so that they can then be filtered in a helm window. UI is also frozen while it is fetching them, hindering productivity.

We need to take advantage of the [server side filtering](https://github.com/OmniSharp/omnisharp-roslyn/blob/2c6c8a481fbdd05c4c06f5ddc720d3a9315d6062/src/OmniSharp.Roslyn.CSharp/Services/Navigation/FindSymbolsService.cs#L26). We currently set this filter to [blank here](https://github.com/OmniSharp/omnisharp-emacs/blob/81b7257bf0d673c5f5365e7b133d11343db51d18/src/omnisharp-helm-integration.el#L59) without giving a chance to the user to type something. Just by typing the first letter of a symbol the results are returned in `10ms` which is a significant improvement.

The server also supports some sort of camel case/fuzzy matching but it clearly needs some improvement.

**Comment by jtbm37** [comment]
I use ReSharper at work, if it were to take 4-6 seconds before it even began to process my navigation filter I'd go mad.

**Comment by sp3ctum** [comment]
This is a really good idea. I think the helm would be nice for this, are you familiar with it?
With helm, it should be easy to trigger a new search, say, after each keypress - then display the results to the user.

**Comment by jtbm37** [comment]
I can't say I am since I am a fairly new to elisp but I figured it out.
I'll have a PR soon.

**Comment by sp3ctum** [comment]
Great! If you get something working don't worry if the tests don't pass. I can take a look at them, or we can do it together somehow.

**Comment by razzmatazz** [comment]
This is actually not even working at all at the moment, so we need to:
 - [ ] add a test for the issue
 - [ ] fix brokeness
 - [ ] implement @jtbm37's solution for server-side filtering
