### ISSUE TITLE
[Roslyn] ability to load .sln-based projects, not just .json

### ISSUE THREAD

**Issue by razzmatazz** [OmniSharp/omnisharp-emacs#227]
Am I correct in my observation that roslyn branch does not support .sln based projects? I noticed the tests were replaced in favor of .proj files as well and omnisharp-start-project now asks for folder only?

**Comment by jtbm37** [comment]
It does but the [server](https://github.com/OmniSharp/omnisharp-roslyn) only support msbuild projects on Windows only.

**Comment by razzmatazz** [comment]
Are you sure that is true? 

Because I was running roslyn in http mode with stock omnisharp-emacs before. However I screwed my setup lately because I was trying to run [roslyn] branch of omnisharp-emacs. Also, I tried running omnisharp-roslyn/artifacts/Omnisharp/default/net451 with the '-s' switch for loading a visual studio solution and it did work, i.e. it spewed output that would confirm it was attempting to load the solution file I have specified.

**Comment by jtbm37** [comment]
Yes you are right. It will work with mono to some **extent**. If you have a Visual Studio solution and you target windows only assemblies or msbuild targets (eg mstest) it will fail to load though.

**Comment by jtbm37** [comment]
With regards to loading the sln project, when starting the server, it should pick up the sln file in the directory you selected and pass it to omnisharp server. Isn't that what you observed ?

**Comment by jtbm37** [comment]
I have also noticed that mono does not work with stdio when passing in an sln file.

**Comment by razzmatazz** [comment]
@jtbm37 yes, when using the 'master' branch of omnisharp-emacs I do observe the behavior that it asks for solution file (and I have multiple ones). Once I specify one the server starts and the debugging information there shows it does load the .sln file and all the corresponding .csprojs.

However (at least on the latest 'dev' commit) it does not work, all endpoints return ```[]``` with 0ms response time, for some reason. Maybe API has changed on the omnisharp-roslyn server and endpoints do not match. I would expect a different response in that case though, not http/200...

*omni-server* buffer excerpt:
```
[0m[32minfo[39m[0m[0m[32m: OmniSharp.Middleware.LoggingMiddleware[0][39m[0m
      /codecheck: 200 0ms
[0m[32minfo[39m[0m[0m[32m: OmniSharp.Middleware.LoggingMiddleware[0][39m[0m
      /autocomplete: 200 0ms
[0m[32minfo[39m[0m[0m[32m: OmniSharp.Middleware.LoggingMiddleware[0][39m[0m
      /typelookup: 200 0ms
```

Maybe thats the way omnisharp-roslyn tries to hint me onto the fact that it doesn't support the .sln/msbuild project system yet?

**Comment by jtbm37** [comment]
@razzmatazz The reason this is happening is because msbuild was not available if not called via mono on other platform than Windows. You'd had to make sure that when omnisharp-emacs called OmniSharp it would start mono instead of the .net core executable.
However this is not a concern anymore as the latest version of omnisharp-roslyn is built with .net core msbuild.
Give it another try with its latest build.

**Comment by razzmatazz** [comment]
@jtbm37 doesn't build from the latest commit on the 'dev' branch (on OS X):
```
log  : Restoring packages for /Users/bob/src/omnisharp-roslyn/src/OmniSharp.Roslyn.CSharp/project.json...
error: Unable to load the service index for source https://www.myget.org/F/roslyn-nightly/api/v3/index.json.
error:   The type initializer for 'Crypto' threw an exception.
error:   The type initializer for 'CryptoInitializer' threw an exception.
error:   Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
error:    (Exception from HRESULT: 0x8007007E)
An error occured when executing task 'Restore'.
```

Some kind of COM error (shudder) – will try later

**Comment by willl** [comment]
@razzmatazz Sounds like you don't have OpenSSL installed. 

https://github.com/dotnet/corefx/issues/9171#issuecomment-225690458

**Comment by razzmatazz** [comment]
@willl – that helped, but now ./build.sh fails when retrieving dependencies:
```
========================================
Restore
========================================
Executing task: Restore
Restoring packages....

Errors in /Users/bob/src/omnisharp-roslyn/src/OmniSharp.MSBuild/project.json
    Unable to resolve 'NuGet.Packaging (>= 3.5.0-rc-1285)' for '.NETStandard,Version=v1.6'.
    Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-rc-1285)' for '.NETStandard,Version=v1.6'.

Errors in /Users/bob/src/omnisharp-roslyn/src/OmniSharp.DotNet/project.json
    Unable to resolve 'NuGet.Packaging (>= 3.5.0-rc-1285)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-rc-1285)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-rc-1285)' for '.NETStandard,Version=v1.6'.
    Unable to resolve 'NuGet.Packaging (>= 3.5.0-rc-1285)' for '.NETStandard,Version=v1.6'.

Errors in /Users/bob/src/omnisharp-roslyn/src/OmniSharp/project.json
    Unable to resolve 'NuGet.Packaging (>= 3.5.0-rc-1285)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-rc-1285)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'NuGet.Packaging (>= 3.5.0-rc-1285)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'NuGet.RuntimeModel (>= 3.5.0-rc-1285)' for '.NETCoreApp,Version=v1.0'.
```

**Comment by willl** [comment]
@razzmatazz That looks similar to what I saw on Travis for a PR that was sent today: https://travis-ci.org/OmniSharp/omnisharp-roslyn/jobs/137386488. 

I'm unsure what the exact issue is, it'll probably be fixed soon if you can wait. You could always grab a release binary built a few days ago from the here: https://github.com/OmniSharp/omnisharp-roslyn/releases

**Comment by willl** [comment]
Looks like a fix for the NuGet issue was merged in a few hours ago: https://github.com/OmniSharp/omnisharp-roslyn/pull/584

**Comment by razzmatazz** [comment]
@willl – thanks that helped!

now, how do I make `omnisharp-emacs/feature-omnisharp-roslyn-support` branch to work with .sln file?

I have:
```
(setq omnisharp-server-executable-path "/Users/bob/src/omnisharp-roslyn/artifacts/publish/OmniSharp/default/netcoreapp1.0/OmniSharp")
```

When I run `omnisharp-start-omnisharp-server` it asks for project folder, not for a .sln file as it did previously with omnisharp-emacs/master.

Entering base directory with .sln file there does this:

OmniServer:
```
OmniSharp: --stdio -s /Users/bob/src/project/src/
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/bob/src/project/src/' on host -1."},"Seq":1,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.DotNet.DotNetProjectSystem","Message":"Initializing in /Users/bob/src/project/src/"},"Seq":2,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.DotNet.DotNetProjectSystem","Message":"Auto package restore: True"},"Seq":3,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.DotNet.DotNetProjectSystem","Message":"Update workspace context"},"Seq":4,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.DotNet.DotNetProjectSystem","Message":"Resolving projects references"},"Seq":5,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.ScriptCs.ScriptCsProjectSystem","Message":"Detecting CSX files in '/Users/bob/src/project/src/'."},"Seq":6,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.ScriptCs.ScriptCsProjectSystem","Message":"Could not find any CSX files"},"Seq":7,"Type":"event"}
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Configuration finished."},"Seq":8,"Type":"event"}
{"Event":"started","Body":null,"Seq":9,"Type":"event"}
```

*omnisharp-debug*:
```
omnisharp--json-read-from-string error: (json-readtable-error) reading input OmniSharp: --stdio -s /Users/bob/src/project/src/
omnisharp--handle-server-message error: (wrong-type-argument listp "The server sent an unknown json message. Inspect the omnisharp-server process buffer to view recent messages from the server. Set ‘omnisharp-debug’ to t and inspect the *omnisharp-debug* buffer for this error specifically."). See the OmniServer process buffer for detailed server output.
INFORMATION: Omnisharp server running using Stdio at location '/Users/bob/src/project/src/' on host -1.
INFORMATION: Initializing in /Users/bob/src/project/src/
INFORMATION: Auto package restore: True
INFORMATION: Update workspace context
INFORMATION: Resolving projects references
INFORMATION: Detecting CSX files in '/Users/bob/src/project/src/'.
INFORMATION: Could not find any CSX files
INFORMATION: Configuration finished.
```

When trying to do autocompletion in the project file by entering a dot after `this`:
```
<...>
Request 9585 did not complete in 2 seconds
```

Should I try the net451 version instead?

**Comment by razzmatazz** [comment]
Btw, I tried starting omnisharp manually via command line:
```
<...>netcoreapp1/OmniSharp --stdio -s /Users/bob/src/project/src/solution.sln
```

and it did load the solution, except that this is over stdio and I don't have a way to make emacs to this (this worked with http version).

So the first problem appears to be that when I do omnisharp-start-omnisharp-server it does not allow me to specify solution file, just project folder (for project.json projects).

Should I make a PR for this? I am not that versed in elisp but I think I can make the change just for this.

**Comment by razzmatazz** [comment]
Here's my PR against feature-omnisharp-roslyn-support.

Now it allows you to specify both a solution file or a .NET Core project directory.

There are definitely some more issues there but I got flycheck and completion to work some of the time already. Yay!

**Comment by jtbm37** [comment]
@razzmatazz good job.

**Comment by razzmatazz** [comment]
Ok, this works now with my PR merged.
