### ISSUE TITLE
Help Documentation Only Shows In Some Cases

### ISSUE THREAD

**Issue by nickecarlo** [OmniSharp/omnisharp-emacs#228]
Hi, I really love omnisharp-emacs and love that it lets me edit, for the most part, in emacs rather than Visual Studio.

I have managed to set up company mode with omnisharp and everything works as expected except for the help documentation. It seems that only some things have documentation showed whereas others do not.

Here's a screenshot of what I see in my emacs:

![company-mode-omnisharp-help](https://cloud.githubusercontent.com/assets/3467100/15655598/e71b8ba8-2674-11e6-9efc-cf2fbd6eb8b4.PNG)

As you can see, the intellisense works fine except for the fact that pressing F1 only shows what namespace it belongs to and not the rest of the documentation.

To clarify what I mean by documentation, this is the same thing in VS:

![intellisense_vs](https://cloud.githubusercontent.com/assets/3467100/15655613/08a1fd3e-2675-11e6-943c-be79e9bd4033.jpg)

The above image shows the same information as what is shown by omnisharp in my emacs plus the msdn documentation.

The settings relevant to omnisharp in my init.el file are:

```
'(omnisharp-auto-complete-want-importable-types t)
'(omnisharp-company-sort-results t)
'(omnisharp-auto-complete-want-documentation t)
```

```
(setq company-begin-commands '(self-insert-command))
  (setq omnisharp-company-do-template-completion t)
  (defun tab-indent-or-complete ()
    (interactive)
    (if (minibufferp)
        (minibuffer-complete)
      (if (or (not yas/minor-mode)
              (null (do-yas-expand)))
          (if (check-expansion)
              (company-complete-common)
            (indent-for-tab-command)))))
```
This was mostly taken from the demo with example omnisharp emacs settings.

I've been trying to find some information on all of this on the internet but can't really find much. Maybe I'm looking at the wrong thing, I'd appreciate any help on this matter.

EDIT: I wanted to add that I'm using the older omnisharp-server found here: https://github.com/OmniSharp/omnisharp-server (I have not changed anything in the code there).

**Comment by sp3ctum** [comment]
Hi, glad it's working out for you (mostly) :)

I too have seen this, and I think it was due to the server not being able to return the appropriate documentation. As the server is no longer supported, I think there will not be a fix there.
