### ISSUE TITLE
Error communicating to the Omniserver Instance

### ISSUE THREAD

**Issue by miragias** [OmniSharp/omnisharp-emacs#233]
Syntax checking not working on my omnisharp. Using debug I found this problem:

> 2016-07-20T01:30:10+0300
> omnisharp--json-read-from-string error: "'c:\Program' is not recognized as an internal or external command,
> operable program or batch file.
> "
> I suppose this has to do with the fact that there is a space after Program in my path, but how do I go about fixing this?

**Comment by sp3ctum** [comment]
What is your `omnisharp-server-executable-path` set to?
You can try adding escaped spaces to it, or try wrapping it in `"` quotes.

**Comment by razzmatazz** [comment]
@miragias  we now have new omnisharp-emacs version released which among other changes has `M-x omnisharp-install-server` command. Please check if using this helps you.

I am closing this issue in the meantime, please reopen if this is still a problem fore you.
