### ISSUE TITLE
Travis builds "Fail to download 'gnu' archive"

### ISSUE THREAD

**Issue by hottrout** [OmniSharp/omnisharp-emacs#241]
Example here https://travis-ci.org/OmniSharp/omnisharp-emacs/builds/153783160#L1655, seems that travis builds are failing to fetch elpa at the moment

**Comment by sp3ctum** [comment]
![](https://cdn.meme.am/instances/500x/61048683.jpg)
there were issues with emacs 24.3 being too old, but it should all be good now.
