### ISSUE TITLE
Missing :modes in syntax checker csharp-omnisharp-codecheck

### ISSUE THREAD

**Issue by logorrhea** [OmniSharp/omnisharp-emacs#246]
Unable to start omnisharp-mode due to the error:
`if: Missing :modes in syntax checker csharp-omnisharp-codecheck`

Environment:
- Debian Jessie
- Spacemacs 0.105.22
- Emacs 24.5.1

**Comment by razzmatazz** [comment]
I made a PR for this on top of the Roslyn branch

**Comment by razzmatazz** [comment]
See https://github.com/OmniSharp/omnisharp-emacs/pull/245

**Comment by logorrhea** [comment]
Oh, ok. Sorry! Any idea of a workaround in the meantime? :(

**Comment by razzmatazz** [comment]
Just apply the patch manually I guess. It's one line.
Tyler Funk <notifications@github.com> schrieb am Di., 13. Sep. 2016 um
18:18:

**Comment by sp3ctum** [comment]
Closing this to avoid duplicates.
