### ISSUE TITLE
 * OmniSharp : Eldoc Fontification * buffer make emacs crash

### ISSUE THREAD

**Issue by sandao** [OmniSharp/omnisharp-emacs#254]
I found  a buffer named  \* OmniSharp : Eldoc Fontification \*  when I use emacs for csharp last time.
and when I switch to this buffer, emacs will crash.
![image](https://cloud.githubusercontent.com/assets/7250358/19260793/15f09230-8fbf-11e6-810d-6afa43e33ec5.png)

**Comment by razzmatazz** [comment]
@sandao sorry for getting to you this late

 - could you confirm you are using the 'roslyn' branch of omnisharp-emacs?
 - what is your platform/emacs version?

**Comment by razzmatazz** [comment]
@sandao please reopen this issue if this is still a problem for you.

we now have a new version released which should behave better
