### ISSUE TITLE
Calls to omnisharp-server seem to hang even though omnisharp-server responds in verbose mode

### ISSUE THREAD

**Issue by kuznero** [OmniSharp/omnisharp-emacs#255]
I am running:
- Ubuntu (actually Elementary OS 0.4 Lokki)
- Curl v7.47
- Spacemacs

**Comment by razzmatazz** [comment]
@kuznero 

can you confirm you are using 'roslyn' version of omnisharp-server? or do you use the one that comes by default with csharp layer on spacemacs?

**Comment by razzmatazz** [comment]
I am closing this as some time has passed since the issue has been created and we now have roslyn version released to MELPA which should behave better.

Please reopen if this is still an issue for you.
