### ISSUE TITLE
Is using omnisharp-emacs in a cygwin environment with omnisharp-rosalyn supported?

### ISSUE THREAD

**Issue by sbroberg** [OmniSharp/omnisharp-emacs#258]
I see in the README there are some instructions on how to get omnisharp-emacs working in a cygwin environment, but these instructions seem specific to using it with the omnisharp server, not the omnisharp-rosalyn server.  A brief scan of the O-R code would seem to indicate that the path-replacements configuration is no longer honored.

If I'm running in a cygwin environment, should I be using the old omnisharp server, despite it appearing to be no longer supported?  Or is there another way to get omnisharp-emacs to work with O-R?  My initial attempts at getting it to work result in emacs hanging when I open a .cs file, likely due to O-R immediately throwing an exception and terminating (which is what it does when I try to run it with a cygwin-style path from the command line).

**Comment by willl** [comment]
There's an omnisharp-roslyn branch here: https://github.com/OmniSharp/omnisharp-emacs/tree/feature-omnisharp-roslyn-support

I'll let someone else chime in about the other stuff though as I'm not an emacs user.

**Comment by jtbm37** [comment]
Yes, use the `feature-omnisharp-roslyn-support` branch.

**Comment by sbroberg** [comment]
How do I use the branch code in my current emacs configuration?  I've omnisharp-emacs installed via melpa, but it's unclear to me what needs to be done to switch to the branch.  Do I just find all the .el files in the branch that correspond to the .el files that are in my ~/.emacs.d/elpa/omnisharp-20160920.2343 directory and copy them there?

**Comment by jtbm37** [comment]
-Remove `omnisharp` package from melpa. Make sure `csharp-mode` is still installed though.
-Clone repo, switch to roslyn branch
- Add this to your init.el
    (add-to-list 'load-path (expand-file-name "~/path/to/repo"))
    (add-hook 'csharp-mode-hook 'omnisharp-mode)

**Comment by sbroberg** [comment]
@jtbm37 , thanks for the info.  I'm still having problems, though.  My init.el config looks like this:

    (require 'company)
    (require 'csharp-mode)
    (add-to-list 'load-path (expand-file-name "~/omnisharp-emacs"))
    (load "omnisharp.el")
    (add-hook 'csharp-mode-hook 'omnisharp-mode)

    (setq omnisharp-server-executable-path "/cygdrive/c/Users/developer/omnisharp-roslyn/artifacts/publish/OmniSharp/default/net451/OmniSharp.exe")
    (setq omnisharp-debug t)

If I navigate to a directory where my .sln file lives, and invoke omnisharp-start-omnisharp-server (/cygdrive/c/Users/developer/Desktop/CSharp Console App/), I get this error in *Messages*:

    Starting OmniSharpServer using project folder/solution file: /cygdrive/c/Users/developer/Desktop/CSharp Console App
    using the server at: /cygdrive/c/Users/developer/omnisharp-roslyn/artifacts/publish/OmniSharp/default/net451/OmniSharp.exe
    The server sent an unknown json message. Inspect the omnisharp-server process buffer to view recent messages from the server. Set ‘omnisharp-debug’ to t and inspect the *omnisharp-debug* buffer for this error specifically.
    omnisharp--handle-server-message error: (wrong-type-argument listp "The server sent an unknown json message. Inspect the omnisharp-server process buffer to view recent messages from the server. Set ‘omnisharp-debug’ to t and inspect the *omnisharp-debug* buffer for this error specifically."). See the OmniServer process buffer for detailed server output.

*omnisharp-debug* contains:
    omnisharp--json-read-from-string error: (json-readtable-error) reading input OmniSharp: --stdio -s C:\Users\developer\Desktop\CSharp Console App
    omnisharp--handle-server-message error: (wrong-type-argument listp "The server sent an unknown json message. Inspect the omnisharp-server process buffer to view recent messages from the server. Set ‘omnisharp-debug’ to t and inspect the *omnisharp-debug* buffer for this error specifically."). See the OmniServer process buffer for detailed server output.
    INFORMATION: Omnisharp server running using Stdio at location 'C:\Users\developer\Desktop\CSharp Console App' on host -1.
    INFORMATION: Initializing in C:\Users\developer\Desktop\CSharp Console App
    INFORMATION: Auto package restore: True
    INFORMATION: Update workspace context
    INFORMATION: Resolving projects references
    INFORMATION: Detecting projects in 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App.sln'.
    INFORMATION: Loading project from 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'.
    INFORMATION: Using toolset 2.0 for 'C:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'
    INFORMATION: Detecting CSX files in 'C:\Users\developer\Desktop\CSharp Console App'.
    INFORMATION: Could not find any CSX files
    INFORMATION: Configuration finished.

Any ideas?

**Comment by jtbm37** [comment]
You can ignore this error. When server starts it sends some messages `omnisharp-emacs` is not expecting, this still has to be pinned down.

Do completion & other functionalities work?

**Comment by sbroberg** [comment]
As far as I can tell, no, the functions don't work.  The project in question is a simple hello world console app:

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// A Hello World! program in C#.
using System;
namespace HelloWorld
{
    class Hello
    {
        static void Main()
        {
            Console.WriteLine("Hello World!");

            // Keep the console window open in debug mode.
            Console.WriteLine("Press any key to exit.");
            Console.ReadKey();
        }
    }
}

If I type "Console." in the main function, I would expect to see an available functions dropdown but none appears.  The only IDE-like behavior I saw was if I started to type the name of a class that was already defined in the same file, a company autocomplete dropdown appeared with the class name as an option.

Even though I have it specified in the csharp-mode-hook, it looks like the .cs buffer is not entering omnisharp mode.  Even if I manually start it once in the buffer (M-x omnisharp-mode), the omnisharp commands don't appears as options when I do C-h b.

**Comment by jtbm37** [comment]
Just to confirm the issue is not with the server. Could you start the server on its own and verify it works?
`OmniSharp.exe -v -s /path/to/solution.sln`

By default, omnisharp starts a web server, so you can query with `curl`. As opposed to `omnisharp-emacs` which passes `--stdio` to the server to start in stdio mode.

Once server is started, send an http request and confirm it returns appropriate result:

`curl -H "Content-Type: application/json" -X POST -d '{"Line":"1","Column":"1", "FileName":"/absolute/path/to/program.cs"}' http://localhost:2000/currentfilemembersastree`

This should list the members of the class in `Filename`

**Comment by sbroberg** [comment]
I can't get the curl command to return anything.  I've tried it with several representations of the path to the file (dos-style, cygwin-style with symlink, cygwin-style without symlink):

```
[WindowsVM:~]$ curl -H "Content-Type: application/json" -X POST -d '{"Line":"1","Column":"1", "FileName":"/home/mobaxterm/Desktop/CSharp\ Console\ App/CSharp\ Console\ App/Program.cs"}' http://localhost:2000/currentfilemembersastree
[WindowsVM:~]$ curl -H "Content-Type: application/json" -X POST -d '{"Line":"1","Column":"1", "FileName":"/cygdrive/c/Users/developer/Desktop/CSharp\ Console\ App/CSharp\ Console\ App/Program.cs"}' http://localhost:2000/currentfilemembersastree
[WindowsVM:~]$ curl -H "Content-Type: application/json" -X POST -d '{"Line":"1","Column":"1", "FileName":"c:\Users\developer\Desktop\CSharp Console App\CSharp Console App\Program.cs"}' http://localhost:2000/currentfilemembersastree

```

Here's the output from the server for these commands:

```
C:\Users\developer\omnisharp-roslyn\artifacts\publish\OmniSharp\default\net451>OmniSharp.exe -v -s "c:\Users\developer\Desktop\CSharp Console App"
OmniSharp: -v -s c:\Users\developer\Desktop\CSharp Console App
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.DotNet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.DotNetTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.MSBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Nuget, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Plugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Roslyn, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Roslyn.CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.ScriptCs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
dbug: OmniSharp.Startup[0]
      Loaded OmniSharp.Stdio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
info: OmniSharp.Startup[0]
      Omnisharp server running on port '2000' at location 'c:\Users\developer\Desktop\CSharp Console App' on host -1.
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Initializing in c:\Users\developer\Desktop\CSharp Console App
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Auto package restore: True
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Update workspace context
info: OmniSharp.DotNet.DotNetProjectSystem[0]
      Resolving projects references
info: OmniSharp#MSBuild[0]
      Detecting projects in 'c:\Users\developer\Desktop\CSharp Console App\CSharp Console App.sln'.
info: OmniSharp#MSBuild[0]
      Loading project from 'c:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'.
info: OmniSharp#ProjectFileInfo[0]
      Using toolset 2.0 for 'c:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll' to 'CSharp Console App'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll' to 'CSharp Console App'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll' to 'CSharp Console App'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.DataSetExtensions.dll' to 'CSharp Console App'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll' to 'CSharp Console App'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll' to 'CSharp Console App'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll' to 'CSharp Console App'.
dbug: OmniSharp.Services.MetadataFileReferenceCache[0]
      Cache miss C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll
dbug: OmniSharp#MSBuild[0]
      Adding reference 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll' to 'CSharp Console App'.
info: OmniSharp.ScriptCs.ScriptCsProjectSystem[0]
      Detecting CSX files in 'c:\Users\developer\Desktop\CSharp Console App'.
info: OmniSharp.ScriptCs.ScriptCsProjectSystem[0]
      Could not find any CSX files
info: OmniSharp.Startup[0]
      Configuration finished.
dbug: OmniSharp.DotNet.DotNetProjectSystem[0]
      GetProjectModel: c:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj
dbug: OmniSharp#MSBuild[0]
      Could not locate project for 'c:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'
dbug: OmniSharp.DotNet.DotNetProjectSystem[0]
      GetProjectModel: c:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj
dbug: OmniSharp#MSBuild[0]
      Could not locate project for 'c:\Users\developer\Desktop\CSharp Console App\CSharp Console App\CSharp Console App.csproj'
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************ Request ************
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      POST - /currentfilemembersastree
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************ Headers ************
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Content-Length - 116
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Content-Type - application/json
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Accept - */*
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Host - localhost:2000
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      User-Agent - curl/7.50.3
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************  Body ************
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      {"Line":"1","Column":"1", "FileName":"/home/mobaxterm/Desktop/CSharp\ Console\ App/CSharp\ Console\ App/Program.cs"}
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /currentfilemembersastree
System.NotSupportedException: Must be able aggregate the response to spread them out across all plugins for /currentfilemembersastree
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleAllRequest>d__19.MoveNext() in C:\Users\developer\omnisharp-roslyn\src\OmniSharp.Host\Middleware\Endpoint\EndpointHandler.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in C:\Users\developer\omnisharp-roslyn\src\OmniSharp.Host\Middleware\Endpoint\EndpointHandler.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext() in C:\Users\developer\omnisharp-roslyn\src\OmniSharp.Host\Middleware\EndpointMiddleware.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************  Response ************
info: OmniSharp.Middleware.LoggingMiddleware[0]
      /currentfilemembersastree: 500 196ms
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************ Request ************
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      POST - /currentfilemembersastree
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************ Headers ************
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Content-Length - 128
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Content-Type - application/json
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Accept - */*
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Host - localhost:2000
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      User-Agent - curl/7.50.3
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************  Body ************
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      {"Line":"1","Column":"1", "FileName":"/cygdrive/c/Users/developer/Desktop/CSharp\ Console\ App/CSharp\ Console\ App/Program.cs"}
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /currentfilemembersastree
System.NotSupportedException: Must be able aggregate the response to spread them out across all plugins for /currentfilemembersastree
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleAllRequest>d__19.MoveNext() in C:\Users\developer\omnisharp-roslyn\src\OmniSharp.Host\Middleware\Endpoint\EndpointHandler.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in C:\Users\developer\omnisharp-roslyn\src\OmniSharp.Host\Middleware\Endpoint\EndpointHandler.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext() in C:\Users\developer\omnisharp-roslyn\src\OmniSharp.Host\Middleware\EndpointMiddleware.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************  Response ************
info: OmniSharp.Middleware.LoggingMiddleware[0]
      /currentfilemembersastree: 500 11ms
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************ Request ************
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      POST - /currentfilemembersastree
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************ Headers ************
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Content-Length - 115
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Content-Type - application/json
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Accept - */*
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      Host - localhost:2000
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      User-Agent - curl/7.50.3
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************  Body ************
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      {"Line":"1","Column":"1", "FileName":"c:\Users\developer\Desktop\CSharp Console App\CSharp Console App\Program.cs"}
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Must be able aggregate the response to spread them out across all plugins for /currentfilemembersastree
System.NotSupportedException: Must be able aggregate the response to spread them out across all plugins for /currentfilemembersastree
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleAllRequest>d__19.MoveNext() in C:\Users\developer\omnisharp-roslyn\src\OmniSharp.Host\Middleware\Endpoint\EndpointHandler.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext() in C:\Users\developer\omnisharp-roslyn\src\OmniSharp.Host\Middleware\Endpoint\EndpointHandler.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext() in C:\Users\developer\omnisharp-roslyn\src\OmniSharp.Host\Middleware\EndpointMiddleware.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
dbug: OmniSharp.Middleware.LoggingMiddleware[0]
      ************  Response ************
info: OmniSharp.Middleware.LoggingMiddleware[0]
      /currentfilemembersastree: 500 11ms



```

**Comment by jtbm37** [comment]
From this line
`info: OmniSharp#MSBuild[0]
      Detecting projects in 'c:\Users\developer\Desktop\CSharp Console App\CSharp Console App.sln'.`

we now know that internally the server expects a windows path in the filename.

Now could you try escaping those blackslashes in the filename of the request ? Like so
`"FileName":"c:\\Users\\developer\\Desktop\\CSharp Console App\\CSharp Console App\\Program.cs"`

If 2 backslashes don't work try 4.

**Comment by sbroberg** [comment]
Ah, I finally got curl to return results - using DOS paths and doubling the slashes (I was writing this as you responded):

```
[WindowsVM:~]$ curl -H "Content-Type: application/json" -X POST -d '{"Line":"1","Column":"1", "FileName":"c:\\Users\\developer\\Desktop\\CSharp Console App\\CSharp Console App\\Program.cs"}' http://localhost:2000/currentfilemembersastree
{"TopLevelTypeDefinitions":[{"ChildNodes":[{"ChildNodes":[],"Location":{"FileName":null,"Line":14,"Column":25,"EndLine":14,"EndColumn":36,"Text":"GetFileInfo","Projects":[]},"Kind":"MethodDeclaration","Features":[],"Projects":["CSharp Console App"]}],"Location":{"FileName":null,"Line":12,"Column":18,"EndLine":12,"EndColumn":28,"Text":"FileSystem","Projects":[]},"Kind":"ClassDeclaration","Features":[],"Projects":["CSharp Console App"]},{"ChildNodes":[{"ChildNodes":[],"Location":{"FileName":null,"Line":21,"Column":16,"EndLine":21,"EndColumn":22,"Text":"Sticks","Projects":[]},"Kind":"ConstructorDeclaration","Features":[],"Projects":["CSharp Console App"]},{"ChildNodes":[],"Location":{"FileName":null,"Line":24,"Column":36,"EndLine":24,"EndColumn":42,"Text":"Sticks","Projects":[]},"Kind":"PropertyDeclaration","Features":[],"Projects":["CSharp Console App"]}],"Location":{"FileName":null,"Line":20,"Column":18,"EndLine":20,"EndColumn":24,"Text":"Sticks","Projects":[]},"Kind":"ClassDeclaration","Features":[],"Projects":["CSharp Console App"]},{"ChildNodes":[{"ChildNodes":[],"Location":{"FileName":null,"Line":29,"Column":21,"EndLine":29,"EndColumn":25,"Text":"Main","Projects":[]},"Kind":"MethodDeclaration","Features":[],"Projects":["CSharp Console App"]}],"Location":{"FileName":null,"Line":27,"Column":11,"EndLine":27,"EndColumn":16,"Text":"Hello","Projects":[]},"Kind":"ClassDeclaration","Features":[],"Projects":["CSharp Console App"]}]}[WindowsVM:~]$ 
```

**Comment by jtbm37** [comment]
This is why `omnisharp-emacs` is not working. It is passing a cygwin path while the server expects a window's.

**Comment by sbroberg** [comment]
Which gets back to my original question - it looks like it doesn't currently support cygwin paths?  I noticed that the start-server command, which accepts a cygwin path in the minibuffer, is sending the location of the .sln dir as a dos path.  Although the same could be done when translating the current buffer's path, I imagine it would be difficult to convert all the paths coming back from the omnipath server (which I presume would be in dos as well) into cygwin paths so that omnisharp-cygwin could interpret them correctly.

**Comment by jtbm37** [comment]
Now it happens that I have a similar setup, my emacs is running in linux while the server is in a windows VM. The way I get it working is by advising the omnisharp functions and changing the unix path into a window's. You can find my dirty hacks [here](https://github.com/jtbm37/dotfiles/blob/master/emacs/private/omnisharp-config.el). Also note this is when working with `omnisharp-use-http` to `t`. You'd have to adjust to `stdio`.

I can understand if you do not wish to go through all this trouble. That's all I can offer for now (or use Emacs windows).

**Comment by jtbm37** [comment]
>Although the same could be done when translating the current buffer's path, I imagine it would be difficult to convert all the paths coming back from the omnipath server (which I presume would be in dos as well) into cygwin paths so that omnisharp-cygwin could interpret them correctly.

My config above should cover all functions. I use this setup at work.

**Comment by sbroberg** [comment]
Thanks for the effort.  I think at this point it makes sense for me to just run the native windows emacs.  My main reason for working in a cygwin environment was originally so that all the external tools were available, but I've since figured out how to get the cygwin tool suite usable from the DOS shell.  I'll move forward with that.

**Comment by sbroberg** [comment]
@jtbm37,

I'm now trying to get the native Windows emacs to work with omnisharp-emacs and omnisharp-rosalyn.  My config now looks like this:

```
(require 'company)
(require 'csharp-mode)
(add-to-list 'load-path (expand-file-name "~/omnisharp-emacs"))
(load "omnisharp.el")
(add-hook 'csharp-mode-hook 'omnisharp-mode)

(setq omnisharp-server-executable-path "c:\\Users\\developer\\omnisharp-roslyn\\artifacts\\publish\\OmniSharp\\default\\net451\\OmniSharp.exe")
(setq omnisharp-debug t)

```

When I attempt to start the server from my .sln directory as above, emacs is now crashing.

The emacs_backtrace.txt file is unuseful:


```
Exception 0xc0000005 at this address:
0117b790

Backtrace:
01151828

Exception 0xc0000005 at this address:
0117b790

Backtrace:
01151828

```

**Comment by jtbm37** [comment]
Unfortunately, I cannot reproduce that on my linux box. I'll give a try on my windows VM and see if that does the same.

**Comment by sbroberg** [comment]
I finally got it working.  Using emacs 25.1.1 (24.4.5 wasn't playing nice) I had to build the roslyn server using DevStudio 2015 (I was previously using 2013), with the 4.6 .net distribution.  That, along with the head of the roslyn feature branch in omnisharp-emacs allowed me to get it working with this git config:

```
(require 'company)
(require 'csharp-mode)
(load-relative "omnisharp-emacs/omnisharp.el")
(add-hook 'csharp-mode-hook 'omnisharp-mode)

(setq omnisharp-server-executable-path "c:\\Users\\developer\\omnisharp-roslyn\\artifacts\\publish\\OmniSharp\\default\\netcoreapp1.0\\OmniSharp.exe")

(use-package company :ensure t :defer t
  :config
  (progn
   (add-to-list 'company-backends 'company-omnisharp)))

```

This setup worked for all variations of emacs on Windows - native NT, cygwin emacs-w32, cywin emacs (terminal) and cygwin emacs-X11.

**Comment by willl** [comment]
Yeah, recent Omnisharp-Roslyn builds need .NET 4.6 to be installed, as you can see here: https://github.com/OmniSharp/omnisharp-roslyn/pull/652 and also https://github.com/OmniSharp/omnisharp-roslyn/pull/669.

**Comment by corngood** [comment]
I was able to get it working on cygwin (with much trouble), so I documented my steps here:

https://github.com/OmniSharp/omnisharp-emacs/wiki/How-to-install-on-cygwin

I needed the net46 version of omnisharp-roslyn for my project.  If you can run it on mono or netcore, you may not have to deal with that IO bug (3).
