### ISSUE TITLE
Omnisharp's checker is not detected by Flycheck

### ISSUE THREAD

**Issue by Wozar** [OmniSharp/omnisharp-emacs#262]
Greetings,

I have some trouble with getting Flycheck to work with OmniSharp. Curl is located in _usr/bin/_. This is also one of the paths associated the `exec-path` variable. Despite that, Flycheck wasn't working, so I tried to type the whole path myself. This didn't work either.

When I enter `flycheck-describe-checker`, Emacs tells me it supports omnisharp-mode only. `flycheck-verify-setup` tells me there are no checkers for the current .cs buffer. `flycheck-verify-checker` tells me that csharp-mode is not supported. I then figured, I'd try to add it by following this [link](http://emacs.stackexchange.com/questions/13392/using-multiple-flycheck-syntax-checkers-in-web-mode). It resulted in an error with a no-good description and when I launched Emacs with argument `--debug-init`, I was greeted with an empty buffer.

I am fairly new to Emacs, so I have no idea if my attempts have been in the right direction, but I am at a loss now.

**Comment by ngscheurich** [comment]
@Wozar, I was able to get around a similar (possibly identical) issue by adding `csharp-mode` to `csharp-omnisharp-checker`’s [list of major modes](https://github.com/OmniSharp/omnisharp-emacs/blob/f956929891e77ba4ce2fb1361129d5d3ebc7bb55/omnisharp.el#L897):

```elisp
:modes (omnisharp-mode csharp-mode)
```

I later found folks with similar issues and solutions in #252 and #259, so this will hopefully be addressed soon.

**Comment by Wozar** [comment]
@ngscheurich I have already tried that. Unfortunately it did not work for me. When I add `csharp-mode` to the `:modes` line, `flycheck-describe-checker` still tells me that it only supports `omnisharp-mode`.

You don't think this could have anything to do with incompatability of the newest version of Emacs (25.1.2)?

**Comment by ngscheurich** [comment]
@Wozar Hmm… Not sure, but potentially—I'm running 25.1.1.

**Comment by Wozar** [comment]
@ngscheurich Fair enough. I appreciate the help anyways.

I also apopoligze for a late response. I have no idea where you can view notifications on GitHub.

**Comment by Wozar** [comment]
Since the non-roslyn part has been abandoned, is this issue still relevant?

**Comment by razzmatazz** [comment]
I don't think so. Unless this is still an issue for you with the roslyn version?

**Comment by Wozar** [comment]
So yesterday I started playing with it again. I tested in a single file and I also cloned the omnisharp-roslyn repo, not to build it, but because it included a .sln file, which I remember is required for at least code completion and syntax checking to work? I didn't actually test with flycheck, but initially I couldn't get company to work, so I'd assume flycheck probably wouldn't work either.

I would guess it didn't work because I didn't have .NET installed. Since I was a little all over the place when trying to fix it, I ended up installing .NET version 2.0 (which is a preview) and version 1.1 from the AUR. I didn't test after each install, so I can't say which resulted in a fix. It still doesn't work for a single file, but testing with the .sln in the omnisharp-roslyn repo, it works.

**Comment by razzmatazz** [comment]
@Wozar you don't need a sln file, a path to plain csproj is sufficient for omnisharp-roslyn to boot up

what platform are you on? if you are using mac or linux then:
 - install mono
 - invoke `M-x omnisharp-install-server` which should setup the server for you (there should be no need to specify `omnisharp-server-executable-path` manually anymore) — see #275

this should be enough to have a working installation (unless I forgot something)

also, there should be no need to install .net core (at least the server version that is installed via `M-x omnisharp-install-server` requires mono and not the .net core version of CLR. those can coexist though

**Comment by Wozar** [comment]
Interesting. I do use Linux (Arch if that matters) and did install it the way you specified. If installing .NET core didn't help, then I haven no idea how it magically started to work.

**Comment by razzmatazz** [comment]
Ok, I have added a note to #275 and closing this if the original issue (flycheck) is working for you now.
