### ISSUE TITLE
why is curl needed?

### ISSUE THREAD

**Issue by bling** [OmniSharp/omnisharp-emacs#263]
i was troubleshooting to see why emacs was freezing when the mode was activated, and it appeared to be because `curl.exe` was blocking for an extended period of time.  the problem was fixed when i installed the official curl instead of using the one bundled with git, which is mentioned in your readme.

however, i wasn't sure why curl was needed, so i took a look at the source code.  it doesn't look like anything fancy is happening.  so i rewrote the function in pure elisp:

``` lisp
(defun omnisharp-post-message-curl (url &optional params)
  (let ((url-request-method "POST")
        (url-request-extra-headers `(("Content-Type" . "application/json")))
        (url-request-data (json-encode params)))
    (with-current-buffer (url-retrieve-synchronously url t t)
      (goto-char (point-min))
      (search-forward-regexp "\n\n")
      (buffer-substring (point) (point-max)))))
```

seems to work...and it's way faster because you don't need a temp file, nor repeatedly opening/closing curl processes.

let me know if there's something i'm missing, otherwise i'm happy to create a PR.

**Comment by bling** [comment]
looks like flycheck can be updated too:

``` lisp
(flycheck-define-generic-checker 'csharp-omnisharp-codecheck
  ""
  :start (lambda (checker callback)
           (let* ((buffer (current-buffer))
                  (json (omnisharp-post-message-curl
                         (concat (omnisharp-get-host) "codecheck")
                         (omnisharp--get-common-params)))
                  (errors (omnisharp--flycheck-error-parser-raw-json json checker buffer)))
             (funcall callback 'finished errors)))
  :error-patterns '((error line-start
                           (file-name) ":"
                           line ":"
                           column
                           " "
                           (message (one-or-more not-newline))))
  :error-parser '(lambda (output checker buffer)
                   (message buffer)
                   (omnisharp--flycheck-error-parser-raw-json
                    output checker buffer))
  :modes 'csharp-mode)
```

**Comment by razzmatazz** [comment]
@bling are you using `master` or `feature-omnisharp-roslyn-support` branch? the support for the old server in `master` is somewhat deprecated..

**Comment by bling** [comment]
master.  that's what melpa is pointing to.

**Comment by razzmatazz** [comment]
`master` of omnisharp-emacs is using the old omnisharp server which is deprecated nowadays.. I think that is what you are using for the server.

it is intended for `feature-omnisharp-roslyn-support` branch to replace current omnisharp-emacs functionality and it support the `omnisharp-roslyn` server only; but it has stdio-based I/O which doesn't need curl. 

what I wanted to say is that `master` in `omnisharp-emacs` will get deprecated soon. documentation on `omnisharp-emacs` probably should be more clear on this though..

**Comment by juergenhoetzel** [comment]
> (with-current-buffer (url-retrieve-synchronously url t t)

This will also block Emacs.. You should consider using async `url-retrieve`.

I implemented *flycheck* support for [flycheck-fsharp](https://github.com/fsharp/emacs-fsharp-mode/blob/master/flycheck-fsharp.el). You might want to check this implementation.

**Comment by kimgronqvist** [comment]
Is it possible to use curl with the roslyn branch of omnisharp-emacs? I cannot run OmniSharp in a process becuase of this bug: https://github.com/OmniSharp/omnisharp-roslyn/issues/647

**Comment by sp3ctum** [comment]
@kimgronqvist there is some support for running omnisharp-roslyn with its special http server interface. If I remember correctly, it allows for two interfaces: the default one is its standard input, and the other one is like in the legacy OmniSharp application (which is to say, it's an http server that can be reached from anywhere the network permits).

I haven't tested this functionality, but I have the impression it works. Someone sent in patches for that at some point, and I kind of forgot about it.

**Comment by razzmatazz** [comment]
@bling can I close this issue? The new version on `master` and released to MELPA no longer requires curl.

**Comment by razzmatazz** [comment]
Actually, I will go ahead and close it. Please reopen if it is still not working for you with the roslyn version.

**Comment by razzmatazz** [comment]
Actually, I will go ahead and close it. Please reopen if it is still not working for you with the roslyn version.
