### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by sp3ctum** [OmniSharp/omnisharp-emacs#265]
Hey everybody!

First I'd like to present my apologies about not being active on omnisharp-emacs for a few months. I know people use it and care about it, and you would have deserved more from me. Lots of questions have come up, and many pull requests have come up too.

I want to announce that I won't be maintaining omnisharp-emacs any longer. This is something I've been putting off for a while. The main reason I'm leaving is I'm no longer working on the .NET platform in my professional life.

In general I can say working with the project is fun for the developer. There are lots of tests too, which should help.

Any takers?

**Comment by razzmatazz** [comment]
I might be able to devote time for this, but I don't have that much knowledge about omnisharp or emacs, newbie to elisp. If thats a non-issue.

**Comment by sp3ctum** [comment]
Sounds good! If you like, I could walk over the code with you on skype or something similar.
Do you have a development environment set up?

**Comment by razzmatazz** [comment]
I would love to have code review over skype to make some sense of the whole picture. I do have development environment ready if you mean working omnisharp-Roslyn + emacs setup.

**Comment by razzmatazz** [comment]
Btw my skype is (name).(surname)

**Comment by sp3ctum** [comment]
Yes, that's exactly what I mean. Sounds good!
I'll add you on Skype and we can schedule a session there.

**Comment by corngood** [comment]
I'm still actively using this (with omnisharp-roslyn on cygwin), so I can help out.

**Comment by sp3ctum** [comment]
Sounds great!

We're planning to have a session on Skype on Sunday this week at 2100
UTC+2. Do you think you could make it?

**Comment by corngood** [comment]
Yeah, I should be able to.  Skype name is corngood.

**Comment by sp3ctum** [comment]
Great, I invited you in Skype.

2017-01-04 23:33 GMT+02:00 David McFarland <notifications@github.com>:

**Comment by juergenhoetzel** [comment]
> I might be able to devote time for this, but I don't have that much knowledge about omnisharp or emacs, newbie to elisp. If thats a non-issue.

It would be nice to get multiple maintainers.

**Comment by sp3ctum** [comment]
We (me, @razzmatazz and @corngood) held a session on Skype, and have scheduled another session for Sunday 29th (this Sunday). @ianbattersby I noticed you said you are keen to jump back into development, so would you like to join in?

**Comment by ianbattersby** [comment]
Hey @sp3ctum. Joining you guys on Sunday seems like a great idea - thank you! I'm certainly very eager to start contributing in some manner again, even if that is just assisting with testing, issues, and reviewing pull-requests :+1:

**Comment by sp3ctum** [comment]
That's great to hear! I sent you a friend request, let me know if you don't see it.
We have a skype group chat going on, I'm going to add you there in advance.

**Comment by sp3ctum** [comment]
@ianbattersby any problems with Skype? I haven't received your friend request there. Just wondering if you're still able to join the discussion today.

**Comment by sp3ctum** [comment]
You can try to add me too, my email address should be the Skype account these days.. I think. It's my first.last@gmail

**Comment by ianbattersby** [comment]
@sp3ctum Yes sorry, I don't use Skype much these days and having issues logging in. Start without me and see if I can get it working :+1:

**Comment by sp3ctum** [comment]
We had a second Skype session, and talked about an upcoming release, supporting the omnisharp-roslyn executable mainly. We also talked about some of the project structure and how it works.

Now I'm happy to announce that in addition to myself, there are three new maintainers/developers:
@razzmatazz 
@corngood 
@ianbattersby 

I'm going to stick around too, mainly for discussion and trying to voice my opinion where needed :+1: 

I'm very happy with how this issue has been handled. I'm closing this as I feel it has served its purpose.

**Comment by kostrse** [comment]
This is fantastic news that the project is not dead.

Would be awesome to see up-to-date environment like branches, milestones, unit-tests?, open issues for grabs, contribution instructions
So those who are less involved could also add their small contributions time to time.

Now it's even hard to understand from where to start from (what branches are current etc.)

**Comment by sp3ctum** [comment]
I agree @kostrse ! I created an issue so the things you mentioned are not lost.

**Comment by josteink** [comment]
If the project now *officially* has new maintainers, I would advice that the note about lacking maintainers be removed from the `README-md`-file.

Currently the front page leaves an impression of uncertainty which may not be beneficial to the project at large.
