### ISSUE TITLE
Issues installing...out of date docs?

### ISSUE THREAD

**Issue by rthompsonj** [OmniSharp/omnisharp-emacs#266]
Hi there!  I've spent the past few hours attempting to get this to work and have had little luck due to a number of factors.  Most notably is that the installation documentation appears to be out of date.  

I was able to get up and "running" after install mono, omnisharp-roslyn, omnisharp-emacs, and adding a csharp hook in my init.el.  However, none of the actual features seem to be functional.  The only clue I have is in my omnisharp-server log:
`
Could not locate MSBuild path. MSBuildProjectSystem will not function properly.
`
Followed by a number of "failed to process project file .....*.csproj" messages.  I'm stuck at this point and sadly will return to monodevelop for the time being.  I installed dotnet SDK for macOS and it doesn't seem to have changed anything.  Anything workarounds I have found relating to the above message end up using `dnvm` which appears to be depreciated in favor of the dotnet SDK, but at the same time I really am not sure because of the lack of docs.

Any help you could provide would be fantastic.  I would be happy to provide a more clear setup process for macOS if I can ever get this thing off the ground.

**Comment by razzmatazz** [comment]
Hi @rthompsonj 

I have it running on macos myself. What version of omnisharp-roslyn are you running? net451 or netcoreapp10 ? Because netcoreapp1.0 has (or at least had issues) loading .csproj project files. I think they are working on it currently (maybe) but anyway, you should try net451 version first.

**Comment by rthompsonj** [comment]
Hi @razzmatazz thanks for the quick response!  I'm running on the dev branch of omnisharp-roslyn (commit fe8d7e24c637d270369a2f954800fd1d14b58304).  I built it from source as advised and was using netcoreapp10 because it was the only one I could get to execute without an error.  But after taking another look I found a bash script in `artifacts/scripts` that executes `mono ~/.omnisharp/local/net46/OmniSharp.exe` which is what I think I should be using.  

The issue then was that `mono` could not be found even though it was clearly in my `PATH` (installed via homebrew and the installer, neither were recognized).  To remedy this I made a symlink in `/usr/bin` that pointed to `/usr/local/bin/mono` and omnisharp-emacs seemed to pick this one up.

However, now whenever I open a .cs file it correctly identifies the sln file, appears to initialize properly, but locks up emacs whenever I start typing.  Any ideas on this one?

**Comment by razzmatazz** [comment]
Mhm, do you use http transport?

And do you use feature-omnisharp-roslyn branch of omnisharp-emacs? Because that is the up-to-date branch of omnisharp-emacs to be used with omnisharp-roslyn

**Comment by razzmatazz** [comment]
@rthompsonj sorry for writing this late, but
 - now we have new version of omnisharp-emacs released to melpa which use the new roslyn version, and
 - `M-x omnisharp-install-server` command is now available which should work on macOS (you need to remove `(setq omnisharp-server-executable-path ..)` from your `init.el` file for the code to pick up the auto-installed server binary)

**Comment by razzmatazz** [comment]
I am closing this as there has been no response for a long time. Please reopen if this is still an issue for you.
