### ISSUE TITLE
Release omnisharp-roslyn support

### ISSUE THREAD

**Issue by corngood** [OmniSharp/omnisharp-emacs#269]
Here we can discuss the logistics of releasing omnisharp support.

* Should the package name be changed on melpa?
  * If not, should the legacy version be released separately?
  * If not, should we do anything to alert users of the change?

* Should we move to version 4.0?

**Comment by razzmatazz** [comment]
Can we get any kind of installation stats from Elpa? I.e. Number of downloads?

**Comment by razzmatazz** [comment]
I would agree on changing version number but that probably doesn't matter that much since package.el doesn't use semver. Or does it?

**Comment by razzmatazz** [comment]
I would also think about these points for the release
 - updated documentation on installation and setup
 - better defaults, preferrably no init.el modification required to make it work out of the box at least on couple of the most popular platforms (requires testing)
 - fixing any spurious messages on startup, users might think it doesn't work?
 - remove support for project.json, since that adventure ended in dotnet land, IIRC..

**Comment by razzmatazz** [comment]
- also, review of existing omnisharp-emacs issues users have reporting for any show-blockers

**Comment by sp3ctum** [comment]
http://melpa.org/#/omnisharp reports 9225 downloads right now. I bet this includes every update people have ever done though. Still a number larger than I would have thought!

**Comment by sp3ctum** [comment]
Wrt. changing the version number: good idea :+1: 
I don't know if package version numbers follow semantic versioning. I think it's up to the developers to decide this.

The next release would definitely be a major upgrade.

**Comment by razzmatazz** [comment]
@sp3ctum I have added https://github.com/OmniSharp/omnisharp-emacs/issues/276 not to forget the roslyn upgrade poses a problem for users using the old/non-roslyn version.

**Comment by razzmatazz** [comment]
I have merged in feature-omnisharp-roslyn support into the main branch in https://github.com/OmniSharp/omnisharp-emacs/pull/297

I think it is time, even though we need to have some issues to be resolved before the next release because people are stumbling upon a wrong branch all the time now.

**Comment by razzmatazz** [comment]
oops, there has been a release on MELPA from the `master` branch that contains the roslyn version now.. but I didn't do it as it wasn't really ready for this..

**Comment by razzmatazz** [comment]
version has been changed and relased to MELPA +stable a long time ago, closing this

**Comment by sp3ctum** [comment]
Yeah, there's been lots of progress on this, mainly thanks to you. Great
job! I'm really impressed and happy the project is doing well.

I can't remember if we discussed this, but I'm not sure how the MELPA
builds work any longer. It's possible the develop branch releases into
MELPA and master gets released into MELPA stable, for example. Sorry about
this, it's quite confusing..

**Comment by razzmatazz** [comment]
@sp3ctum thanks!

yes, we'll probably have to split into master and develop branches to get stable.melpa.org working separately from master, but maybe not.. maybe tagging is enough here..
