### ISSUE TITLE
Doesn't initialize well with Desktop mode

### ISSUE THREAD

**Issue by jojojames** [OmniSharp/omnisharp-emacs#272]
Repro:

1. Open 1+ csharp files with Emacs.
2. Call desktop-save
3. Open Emacs and call desktop-read

For every file opened, it'll ask to kill/restart Omnisharp server.

**Comment by razzmatazz** [comment]
Tried on the `roslyn` branch, apparently it works ok for multiple files as the new version just emits a message to *messages* and doesn't ask the user to start server for each of the files opened with desktop-read.

@jojojames – can you confirm it works for you too on the https://github.com/OmniSharp/omnisharp-emacs/tree/feature-omnisharp-roslyn-support branch?

**Comment by jojojames** [comment]
I will see if I can test once I have some more time.

**Comment by jojojames** [comment]
Hmnn, haven't been able to get the Rosyln+Emacs working with the new Rosyln server on a Xamarin codebase. I'll close this for now.
