### ISSUE TITLE
Some kind of notification to non-roslyn users needed for omnisharp-emacs roslyn release

### ISSUE THREAD

**Issue by razzmatazz** [OmniSharp/omnisharp-emacs#276]
We're planning to release the `roslyn` branch of omnisharp-emacs as the default on MELPA.

This will pose a surprise to users who are still using the old version + old server and thus we need to have some kind of instructions prepared for them so they:
 - know what is happening and why we broke their setup;
 - provide upgrade instructions;
 - provide an alternative instruction if they do not wish to upgrade to the new roslyn server/omnisharp-emacs version (i.e. checkout old code from github, instead of from MELPA?).

**Comment by sp3ctum** [comment]
Yep, great idea! Have you thought about how to do it technically? If it showed a message like "go to this issue/wiki page" to find out more, the information could be updated independently of the release cycle of the plugin itself. 

Just an idea ☺️

**Comment by razzmatazz** [comment]
Probably a message on start server interactive invocation? Like you said.

Yeah, this is probably lowest effort thing we can do sans any setup wizard or server binary download we don't have yet.

Now what would be the logic to detect such cases? If omnisharp-server-path is set and some new customizable, say omnisharp-uses-Roslyn is set? Not sure..

What do you think?

**Comment by razzmatazz** [comment]
And yes, an issue page would be better than wiki page since people can voice their opinion/fixes on issue page vs wiki page.

**Comment by razzmatazz** [comment]
This is issue page that we will emit on the upgrade message:
 - https://github.com/OmniSharp/omnisharp-emacs/issues/279

Still needs to be updated with upgrade instructions and such, – pretty much empty now.

**Comment by sp3ctum** [comment]
Yeah, the "migration detection" can be programmatic like that, but even easier might be to have some `omnisharp-have-seen-migration-message` customization variable. Out of the box that would be falsey, and in that case a message would be displayed when starting.

The message could say like "add this piece of initialization code to your configuration to hide this message on startup: `(setq omnisharp-have-seen-migration-message t)`.

This way it's basically a "heads up" that a lot of things have changed.

**Comment by razzmatazz** [comment]
Closing this corresponding issue #279 is closed too
