### ISSUE TITLE
flycheck mode should be enabled automatically for .cs files

### ISSUE THREAD

**Issue by alistair** [OmniSharp/omnisharp-emacs#285]
When opening a csharp file flycheck mode should be enabled by default.

Currently you have to either do something similar to

```lisp
 (defun sm-csharp-mode-setup ()
   (setq indent-tabs-mode nil)
   (setq c-syntactic-indentation t)
   (c-set-style "ellemtel")
   (setq c-basic-offset 4)
   (setq truncate-lines t)
   (setq tab-width 4)
   (setq evil-shift-width 4)
   (local-set-key (kbd "C-c C-c") 'recompile)
   (flycheck-mode))

   (add-hook 'csharp-mode-hook 'sm-csharp-mode-setup t)
```

or run the command directly.

Attempting to find out on the spacemacs gitter if this should be done in the spacemacs layer or he.

**Comment by razzmatazz** [comment]
It seems like language support layers just add a hook on `packages.el` in their `+lang` directory in spacemacs to support flycheck. 

I have made a PR that does just that on https://github.com/syl20bnr/spacemacs/pull/8623

Closing this issue as on non-spacemacs installation user is supposed to do some setup himself. We probably want to provide some examples on this but this is probably out of scope for this issue.
