### ISSUE TITLE
Bring back sln discovery for omnisharp-roslyn branch

### ISSUE THREAD

**Issue by alistair** [OmniSharp/omnisharp-emacs#286]
As dotnet is moving back to having sln's and csproj files we should re-enable the functionality to find solution files.

**Comment by razzmatazz** [comment]
yes, this would be nice to have.. we can probably just port over the code from legacy branch; don't know if it has been removed on legacy but we can find this in repo change log

it would be lovely if you could provide a PR. otherwise this is not NR 1 priority for me at the moment
