### ISSUE TITLE
run-code-action doesnt display menu correct on first time

### ISSUE THREAD

**Issue by alistair** [OmniSharp/omnisharp-emacs#292]
Steps to Produce:

1)  Take a working solution
2)  Remove a using statement e.g. Newtonsoft.Json ( or others )
3)  Start omnisharp or reload solution
4)  Run code actions on some type like JsonConvert for the example in 2

Expected:
To see the menu item with different options ( one should be to add using statement)

Actual:
Just see "Run Code action:"

Logs;

> The server sent an unknown json message. Inspect the omnisharp-server process buffer to view recent messages from the server. Set `omnisharp-debug' to t and inspect the *omnisharp-debug* buffer for this error specifically.
> omnisharp--handle-server-message error: (wrong-type-argument listp "The server sent an unknown json message. Inspect the omnisharp-server process buffer to view recent messages from the server. Set `omnisharp-debug' to t and inspect the *omnisharp-debug* buffer for this error specifically."). See the OmniServer process buffer for detailed server output.
> Error in post-command-hook (ido-exhibit): (wrong-type-argument stringp nil)
> error in process filter: Quit [2 times]

**Comment by razzmatazz** [comment]
@alistair  – this is on roslyn version/branch, right?

to me this smells to be related to #283

will take a look

**Comment by razzmatazz** [comment]
Hmm, I cannot replicate this using my spacemacs config, but I see in your logs you have an error message that says something about `ido`. Could you try to figure out where that error comes from – using `(setq debug-on-error t)` to trigger debugger on error?

Otherwise, can you post your .spacemacs?

**Comment by alistair** [comment]
Here is my spacemacs config. 

https://github.com/alistair/dotfiles/blob/master/_spacemacs

Adding (setq debug-on-error t) into my user-config doesnt cause it to do anything ( aka no actual error it seems so it doesnt debug )

**Comment by razzmatazz** [comment]
Sorry, cannot replicate this myself.. A lot of things has changed since then.

Are you using the latest `develop` branch of the spacemacs (0.300.x) or the regular `master` one (0.200.x) ? If not, I would recomment you try the `develop` branch as I have fixed a couple of issues on the `csharp` layer too..

**Comment by razzmatazz** [comment]
Sorry for getting to this so late.

**Comment by alistair** [comment]
Im going to close this as i'm not sure Im getting it anymore
