### ISSUE TITLE
OmniSharp Meeting Monday April 3rd, 2017 @ 18:00 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/omnisharp-emacs#295]
Hey Guys,

I know you're off doing your own thing most of the time, but we are having a team meeting and you're welcome to join if you wish!

Let me know if you have an email to send a calendar invite to, and I'll be pleased to do that as well.

See: https://github.com/OmniSharp/OmniSharp/issues/17

**Comment by razzmatazz** [comment]
@david-driscoll 
sorry, could not attend
