### ISSUE TITLE
omnisharp-build-in-emacs not working now

### ISSUE THREAD

**Issue by lwx5924** [OmniSharp/omnisharp-emacs#302]
, c c to compile the solution but get the error

command-execute: Wrong type argument: commandp, omnisharp-build-in-emacs

**Comment by razzmatazz** [comment]
this is on spacemacs, right?

this commands has not been ported from the legacy omnisharp server (yet).

marking it as a regression

**Comment by ricardomga** [comment]
any work around?

**Comment by lwx5924** [comment]
@razzmatazz 

Thanks for your response.

Yes, this is on spacemacs.

But it worked before.  I compare the right run and the failed run.

When it has csharp project file *.sln it worked.
When it only has *.csproj, it not worked.

So, I think omnisharp it need to *.sln files.

**Comment by thorlacius** [comment]
On Spacemacs, I get this error message from `omnisharp-build-in-emacs`, `omnisharp-unit-test-all` and `omnisharp-unit-test-single`. Should I open a new, identical ticket?

Flycheck works great, by the way, after I manually installed the x86 prebuilt OmniSharp server for Windows.

**Comment by mslot** [comment]
> On Spacemacs, I get this error message from `omnisharp-build-in-emacs`, `omnisharp-unit-test-all` and `omnisharp-unit-test-single`. Should I open a new, identical ticket?
> 
> Flycheck works great, by the way, after I manually installed the x86 prebuilt OmniSharp server for Windows.

I also get same error for all unit tests. Did you create a ticket?
