### ISSUE TITLE
Current release fails to install from MELPA stable

### ISSUE THREAD

**Issue by ccharles** [OmniSharp/omnisharp-emacs#310]
The current stable release (version 3.9, from April, 2015) fails to install from MELPA stable:

> Debugger entered--Lisp error: (error "Need package ‘dash-20141201.2206’, but only 2.13.0 is available")

It looks like the relevant dependency has [already been updated][1]. Please consider tagging a new release so MELPA stable users can install omnisharp.

[1]: https://github.com/OmniSharp/omnisharp-emacs/commit/10d6f298e9264aa0785a543c1cc8b076cf5d169d

**Comment by razzmatazz** [comment]
thanks! forgot about this..

ok, just made a tagged release for v4.0, lets see it melpa stable updates itself..

**Comment by ccharles** [comment]
[Looks good to me][1]. Thanks for the rapid response!

[1]: https://stable.melpa.org/#/omnisharp
