### ISSUE TITLE
csharp layer installs non-roslyn version of omnisharp-emacs.

### ISSUE THREAD

**Issue by WeiLi-TW** [OmniSharp/omnisharp-emacs#318]
it cause can't use most of key bindings, how to fix it?

**Comment by razzmatazz** [comment]
@WeiLi-TW sorry for replying this late, but a lot of the bindings in the spacemacs layer are not yet implemented on the new omnisharp-emacs version that is based on roslyn.

Do you have any particular command that you need?

**Comment by razzmatazz** [comment]
btw, this is on spacemacs, right?

**Comment by WeiLi-TW** [comment]
@razzmatazz yes, this is on spacemacs. if i want develop c# via spacemacs, should i install omnisharp-servers for use omnisharp-emacs.

**Comment by razzmatazz** [comment]
@WeiLi-TW — yes, with the latest version (on macOS and Linux) you can install the server automatically with M-x `omnisharp-install-server` command. so the setup procedure shouldn't be this difficult anymore
