### ISSUE TITLE
No license information - why?

### ISSUE THREAD

**Issue by matsl** [OmniSharp/omnisharp-emacs#337]
Hi, please excuse me for contacting you this way but it was suggest on the Slack #general channel, https://omnisharp.slack.com/archives/C0RE3QY1K/p1500705876720193,  that this could be the best way to reach omnisharp-emacs developers. 

I'm looking into why some emacs packages on MELPA does not have any license. omnisharp-emacs is such a package. This small investigation was triggered by this thread on emacs-devel https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg00341.html Your project stands out in that it has many contributors but still no license. That is interesting. I'd would appreciate very much if you would like to comment on why this is so. 

Yours Mats

**Comment by razzmatazz** [comment]
hi @matsl, we do have GPLv3 header on omnisharp.el, — see https://github.com/OmniSharp/omnisharp-emacs/blob/master/omnisharp.el

but not on the other package sub files — omnisharp-*.el is this a problem?

not sure how can I mark the license on MELPA, do we need to set some special `;;;` comment on omnisharp.el for MELPA to pick up the license?

**Comment by matsl** [comment]
Hi @razzmatazz Thanks for helping out and thanks for pointing that out that your intent is to have it under GPLv3. I missed that on the copyright line.

I'm not giving advice at the moment for how you should do. I'm just trying to get a picture of why some packages are not licensed properly. If yours is in the category remains to see. My conclusion so far is that your intent is to have it licensed under GPLv3.

You can find more info here how to use the license: https://www.gnu.org/licenses/gpl-howto.html. It is a short and good read on the subject. 

What stands out to me is that: 
- GPLv3 is a license and is not part of the copyright info, 
- the copying permission statement text should be part of every file
- that the license text itself often is included in a file "COPYING"  in the distribution and 
- it is also recommended to include as part of the copying statement, in each file that is, the text "version 3 of the License, or (at your option) any later version." (Often known as GPLv3+)

I don't know about MELPA but from looking at the info about the packages as you get after running list-packages there does not seem to be any license info there. That is in any case not the problem my investigation is addressing.

**Comment by razzmatazz** [comment]
follow up in https://github.com/OmniSharp/omnisharp-emacs/issues/341
