### ISSUE TITLE
Please specify the license for this package

### ISSUE THREAD

**Issue by tarsius** [OmniSharp/omnisharp-emacs#341]
Could you please specify the license used by this package?

Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this to the library header:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

You could also, or instead, add a `LICENSE` file containing the [text of the GPL-3](https://www.gnu.org/licenses/gpl-3.0.txt). But if you only add that file, then the "or (at your option) any later version" bit won't be known.  I recommend that you do *both*.

If this is too noisy for you, then you could also add one of these following lines to the header.  (I do however recommend against doing *only* that - a judge might decide that this is not sufficient.)

```
;; License: GNU General Public License version 3, or (at your option) any later version
;; License: GNU General Public License version 3, or any later version
;; License: GNU GPL version 3, or (at your option) any later version
;; License: GPL version 3, or (at your option) any later version
;; License: GPL version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version
;; License: GPL-3+
```

**Comment by razzmatazz** [comment]
@tarsius I probably need to add this header to each of .el files, right? 

because this is a multifile package.. 

btw, we already have a license declaration on this line ("GPLv3"):
 - https://github.com/OmniSharp/omnisharp-emacs/blob/master/omnisharp.el#L3

will update the package as you've suggested

**Comment by sp3ctum** [comment]
Hmm I don't know if it's all right that the "copyright" is under my name, as I've only been reading diffs and commenting, not providing any code. I wonder if this should be changed.

**Comment by tarsius** [comment]
> I probably need to add this header to each of .el files, right?

That's preferred, yes.

> Hmm I don't know if it's all right that the "copyright" is under my name,

`;; Copyright (C) NNNN-MMMM A. U. Thor and contributors` is an option. Magit uses `;; Copyright (C) 2008-2017  The Magit Project Contributors`.

**Comment by tarsius** [comment]
> btw, we already have a license declaration on this line ("GPLv3"):

I recommend you remove that. If you don't want to add the full permission statement to all secondary libraries, then it would be better to use a separate `;; License: ...` header keyword instead of this.

**Comment by razzmatazz** [comment]
@tarsius I've added the LICENSE file (GPLv3) and then headers to most of the files

Could you take a quick look if this is OK and we can close the issue?

I probably need to change license on github page too..

**Comment by razzmatazz** [comment]
oh, github automatically has detected the license from the license file

<img width="1023" alt="bildschirmfoto 2017-08-03 um 12 29 41" src="https://user-images.githubusercontent.com/563556/28937230-752d0a6e-7847-11e7-8528-32c512aa0016.png">

**Comment by tarsius** [comment]
My tools can pick up the license too now. Thanks!

**Comment by razzmatazz** [comment]
@tarsius good, and thanks for all your work; I saw the thread on emacs-dev
