### ISSUE TITLE
Error in response handler with company-mode

### ISSUE THREAD

**Issue by raphm** [OmniSharp/omnisharp-emacs#354]
I just installed omnisharp-emacs last night (8/14/2017) using the instructions in the readme. Server installation was done using `omnisharp-install-server`.

When I start the omnisharp server and use company-mode to attempt to get an autocomplete value in a C# file, I see the following error in the emacs message buffer:

```
omnisharp: OmniSharp.Startup, Configuration finished.
Company mode enabled in current buffer

omnisharp--handle-server-response-packet error: 
(invalid-function omnisharp--setq-and-restore).

Tried to handle this packet: 
((Request_seq . 5) (Command . "autocomplete") (Running . t) (Success . t) (Message) (Body . []) (Seq . 23) (Type . "response"))

This can mean an error in the handler function:
#[257 "\211^Q\300\205	^@\300^A!\207" [#[257 "\304
^K\301\300^E!!#\207" [#[257 "\303\304	\"
\305=\203^Q^@\306\300^B\"\202^R^@\211\207" [#("Transf" 0 1 (fontified t) 1 2 (fontified t) 2 3 (fontified t) 3 4 (fontified t) 4 5 (fontified t) 5 6 (fontified t)) omnisharp--last-buffer-specific-auto-complete-result omnisharp-company-match-type mapcar omnisharp--make-company-completion company-match-simple all-completions] 5 "

(fn RESULT)"] #[257 "\211\203^K^@\301\242\307=\204^Q^@\301^A\240\207\306^V^K\300\310^B!BC^V^L\311\216\312\302\303\304\305$)\207" [#("Transf" 0 1 (fontified t) 1 2 (fontified t) 2 3 (fontified t) 3 4 (fontified t) 4 5 (fontified t) 5 6 (fontified t)) (nil) #<buffer FaceManager.cs> #<window 3 on FaceManager.cs> 996 734 company-omnisharp done company--preprocess-candidates #[0 "^H?\205
^@\303\211^Q\211^R\207" [company-candidates company-backend company-candidates-cache nil] 3] company-idle-begin company-backend company-candidates-cache] 6 "

(fn CANDIDATES)"] completion-ignore-case omnisharp-company-ignore-case omnisharp--setq-and-restore] 7 "

(fn RESULT)"] omnisharp--last-buffer-specific-auto-complete-result] 3 "

(fn AUTO-COMPLETE-RESPONSE)"]
```
This is most likely an error in my environment, so (a) what other information would be helpful to debug this, and (b) is there an obvious place to start? I spent some time digging into the autocomplete pathway last night but haven't seen anything obvious.

Omnisharp server version is 1.22.0; omnisharp-emacs version is:

`omnisharp          20170814.1114 installed             Omnicompletion (intellisense) and more for C#`

Happy to try anything and return results, if it would be helpful. Or if you point me in the right direction I can see if I can figure it out.

Thank you very much!

**Comment by razzmatazz** [comment]
This looks strange... and related to last changes I made. I am on vacation
right now and don't have a pc nearby. But could you tell:
- what is your emacs version?
- if you press "F1 f" and then enter "omnisharp--setq-and-restore" – do.
you get description for a macro or an error?
Raph <notifications@github.com> schrieb am Di. 15. Aug. 2017 um 09:00:

**Comment by razzmatazz** [comment]
Also, if this takes too long to resolve you could try omnisharp-emacs 4.1 version from stable.melpa.org

**Comment by jfmcbrayer** [comment]
Ah, I get this as well. Emacs is 25.2.1 (Windows, 64-bit). Omnisharp is 1.22.0 of omnisharp-win-x86-net46. 

omnisharp--setq-and-restore is a Lisp macro in omnisharp-utils.el.

**Comment by raphm** [comment]
Hi! No worries, I will try omnisharp-emacs 4.1 later tonight. And do not interrupt the vacation; this is not urgent (unless you consider having to use Monodevelop urgent...  :)  )

Emacs version is GNU Emacs 25.2.1 (x86_64-w64-mingw32) (2017-04-24).
F1 f and then omnisharp--setq-and-restore returns [No match].

If I eval it by hand (inside omnisharp-utils) and then re-eval omnisharp--do-server-start and omnisharp--get-company-candidates, I see:

```omnisharp: OmniSharp.Startup, Omnisharp server running using Stdio at location ’c:/Users/Test User/src/paper-arena/’ on host -1.
<-- OmniSharp server error: The project system ’OmniSharp.MSBuild.MSBuildProjectSystem’ threw exception during initialization.
omnisharp: OmniSharp.Startup, Configuration finished.
```
Thank you for all the work on this project!

**Comment by razzmatazz** [comment]
@raphm the issue with the macro error should be gone now with the PR from @juergenhoetzel

as for the server error problem, what happens if you run the server manually, with:
 - `~/.emacs.d/.cache/omnisharp/server/v1.22.0/omnisharp --stdio -s ~/src/solution-file|project-file` ?

on Windows you probably start it from somewhere in C:\Users:
 - C:\Users\User\.emacs.d\omnisharp\server\v.1.22.0\OmniSharp.exe --stdio -s c:\solution-file-path.sln

this should spew out more diagnostics output for you to diagnose why omnisharp is crashing..

and then, if it is not obvious, I think you should contact folks at @ https://github.com/OmniSharp/omnisharp-roslyn

**Comment by raphm** [comment]
Yes, the PR from @juergenhoetzel resolved this. The server problem is fixed with the latest version of omnisharp-roslyn (1.23.2). Thank you very much!
