### ISSUE TITLE
omnisharp: OmniSharp server terminated

### ISSUE THREAD

**Issue by kirkins** [OmniSharp/omnisharp-emacs#361]
I've installed omnisharp-emacs and then run `M-x omnisharp-start-omnisharp-server RET`, which shows a directory selection, I pick the directory with the `.sln` file. After I hit enter it says `omnisharp: OmniSharp server terminated`.

Anyone know what I'm doing wrong here? I couldn't find anything in the docs. I'm on standard Ubuntu 16.04.

**Comment by razzmatazz** [comment]
- do you have mono installed? what is the output of `$ mono --version` on your terminal? for me (on macOS though) it is:
```
bob@mbp ~ $ mono --version
Mono JIT compiler version 5.2.0.215 (d15-3/da80840 Thu Jul 20 16:43:07 EDT 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen (concurrent by default)
```

5.0+ should be ok

 - what is the output of omnisharp server when run directly from the terminal, e.g. with command line:
```
$ bob@mbp ~ $ ~/.emacs.d/.cache/omnisharp/server/v1.22.0/omnisharp --stdio -s /Users/bob/src/printlog/src/printlog.sln
```

For me the output is:
```
OmniSharp: --stdio -s /Users/bob/<path-to-project.sln>
{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/bob/<project>' on host -1."},"Seq":1,"Type":"event"}
...
```

the messages should help figure out why the server could be failing to start

 - i have created an issue #362 so anything that is found here can go there

**Comment by ylluminarious** [comment]
@kirkins @razzmatazz I just had the same exact issue (albeit on Mac OS X), and the cause of the problem was that my `omnisharp-server-executable-path` was set to `"/usr/local/bin/omnisharp"` (as I was previously using the homebrew package for omnisharp). As soon as I unset that variable, everything worked fine again.

**Comment by razzmatazz** [comment]
@ylluminarious so it was pointing to a non-working/missing binary? Or was it because `omnisharp-server-executable-path` is not working anymore? (worried)

**Comment by ylluminarious** [comment]
@razzmatazz The binary was missing (I uninstalled the package before trying the new installation method).

**Comment by razzmatazz** [comment]
new releases of omnisharp-emacs use mono bundled with the server binary, so we shouldn't have these problems anymore

please reopen if this problem is still valid for any of you..
