### ISSUE TITLE
omnisharp-fix-code-issue-at-point is not defined

### ISSUE THREAD

**Issue by ylluminarious** [OmniSharp/omnisharp-emacs#367]
When trying to run `omnisharp-fix-code-issue-at-point`, I get an error:

```
Symbol’s function definition is void: omnisharp-fix-code-issue-at-point
```

Upon doing a cursory search through the codebase, it seems that this function is actually not defined anywhere. Yet this function is advertised in `doc/features.md`, so I'm not sure why it's not working, let alone not defined.

**Comment by razzmatazz** [comment]
this is probably a leftover from an older version;
 - `omnisharp-emacs` was rewritten for omnisharp-roslyn and thus doc/features.md refers to old functionality — will remove it

sorry, should should look at `omnisharp-run-code-action-refactoring` now

**Comment by ylluminarious** [comment]
@razzmatazz Ok, thanks for the info.
