### ISSUE TITLE
dotnet cli version check fails at integration test.

### ISSUE THREAD

**Issue by supermomonga** [OmniSharp/omnisharp-emacs#371]
In my local machine, test fails because it can't pass dotnet cli's version check in `run-integration-tests.sh`.

It shows below log.

```
./test-stuff/run-integration-tests.sh
'dotnet --version' reports: 1.0.4
Must install the .NET CLI 1.1.* http://dotnet.github.io/
```

All tests will be executed inside Docker container, and the Dockerfile we use is based on `microsoft/dotnet:1.1.2-sdk` image.

While we use `microsoft/dotnet:1.1.2-sdk` image, `dotnet --version` should return `1.0.4`.

```sh
$ docker run --rm microsoft/dotnet:1.1.2-sdk dotnet --version
1.0.4
```

I thought [this commit](https://github.com/OmniSharp/omnisharp-emacs/commit/8749f70b3a1ec5f837547071d8c1ec13336be190) causes this, but [in travis](https://travis-ci.org/OmniSharp/omnisharp-emacs/builds/266357679#L4194-L4195), `dotnet --version` returns `1.1.0`.

Travis is also using docker container based on `microsoft/dotnet:1.1.2-sdk` as mentioned above, so I think it should return `1.0.4`, but actually it returns `1.1.0`... I'm confused.

---

@razzmatazz Can you run tests in your local machine? and do you know the detailed information about [travis breakage](https://github.com/OmniSharp/omnisharp-emacs/pull/357)?

**Comment by razzmatazz** [comment]
@supermomonga It works for me (on my local machine).

I think I made some changes to the travis stuff a month or so ago and you need to delete preexisting images on you machine (omnisharp-* ones) as it doesn't detect the change automatically when building. Can't remember the reason, though :)

And I have restarted the build No 642 on your PR (https://travis-ci.org/OmniSharp/omnisharp-emacs/builds/273423208?utm_source=github_status&utm_medium=notification)

**Comment by supermomonga** [comment]
@razzmatazz Thanks!

You right. I tried `docker-compose build --no-cache` but as you said, I should execute `docker pull microsoft/dotnet:1.1.2-sdk` before that. After pulling latest image of `microsoft/dotnet:1.1.2-sdk`, it works fine!
