### ISSUE TITLE
I can't figure out why omnisharp-emacs won't acknowledge one project.

### ISSUE THREAD

**Issue by phoenixanimations** [OmniSharp/omnisharp-emacs#374]
Hi I've stumble across a bizarre bug. I have a project, (called MultipleChoiceGameV4) and when running the omnisharp server while I do not get any errors, none of the syntax gets highlighted or checked. When I try to do something like `omnisharp-go-to-definition` I get: `Cannot go to definition as none was returned by the API.` This project is in Unity3D, and other projects that are Unity3D do get recognized. The `omnisharp-check-alive-status` returns `Server is alive and well. Happy coding!`

So the weird thing is when I drag these files individually to another Unity project (just the literal .cs files no .meta) it will be alright until I move things around (either create new folders or move the files to other folders). Then omnisharp will stop working for that project as well (even for files unrelated to the project). Sadly this is the hardest to track down behavior wise, as I don't know exactly what makes omnisharp stop responding in the new project. But I do know this only happens when I move the MultipleChoiceGameV4 files. I've moved .cs files in other projects with no problem.

So here are the things I've tried: I've deleted: MultipleChoiceGameV4.sln, Assembly-CSharp-Editor.csproj, Assembly-CSharp.csproj and had Unity auto generate new ones. Uninstalled omnisharp/delete the cache folder and reinstalled. Tried both melpa-stable and melpa versions. Again it works great, until I start on MultipleChoiceGameV4.

I've tried to move the files from the old version to a new location 4 times and each one eventually broke. Although not at first which is rather frustrating. Any suggestions for the next step? Thanks for the help either way.

**Comment by razzmatazz** [comment]
Hi @phoenixanimations.

Have you tried using the latest version of the omnisharp-roslyn server? You can `customize` the `omnisharp-expected-server-version` variable to something like 1.24.0 (see https://github.com/OmniSharp/omnisharp-roslyn/releases for the list of version numbers) or set `omnisharp-server-executable-path` to the server binary downloaded/built.

Otherwise I would suggest you register an issue with https://github.com/OmniSharp/omnisharp-roslyn as it appears to be an issue related to language server itself.

**Comment by phoenixanimations** [comment]
Switching to 1.24.0 solved it, thank you so much. So I'm not sure what that means but if there is any additional info you might need just let me know. Otherwise this issue can be closed.

**Comment by razzmatazz** [comment]
@phoenixanimations i'll keep it for a while remember me to upgrade server version in omnisharp.el

**Comment by razzmatazz** [comment]
I have updated omnisharp.el to require version 1.24
