### ISSUE TITLE
provide call to connect to running Omnisharp server

### ISSUE THREAD

**Issue by lwiechec** [OmniSharp/omnisharp-emacs#375]
Looks like I cannot use `omnisharp-emacs` with OmniSharp server running from [Docker container](https://hub.docker.com/r/erikap/omnisharp-server/) - the `omnisharp-emacs` insists on connecting to the server first.

Lots of the code depends on the [list returned](https://github.com/OmniSharp/omnisharp-emacs/blob/b425270bed93b427ff519d6f51ad1d97531a0a92/omnisharp-server-management.el#L36) from `make-omnisharp--server-info` but would it be possible to just use the server already started?

**Comment by razzmatazz** [comment]
@lwiechec this container seems to be based on a non-roslyn server and the new omnisharp-roslyn server (https://github.com/OmniSharp/omnisharp-roslyn) is phasing out http comm with the client.

I think you need to alter the container somehow to allow stdio comm and then we'd need to some changes to the omnisharp-emacs code to launch the docker container with proper volumes mounted instead.. So this does not appear trivial unless you want to chip in and help us :)

**Comment by razzmatazz** [comment]
Btw, what is your use case? Why running native server is not ok for you? I am interested in all use cases.

**Comment by lwiechec** [comment]
The real reason was that I had some troubles compiling `ominsharp-roslyn` on my Linux box, so I thought about the 'easiest' solution - just spin up the container. In the meantime, I want back and - just used the released, compiled version of the server. After that - `omnisharp-emacs` works very good. Thanks for it!

**Comment by razzmatazz** [comment]
Ok, closing then
