### ISSUE TITLE
Omnisharp v1.24.0 install fails on Windows

### ISSUE THREAD

**Issue by kirill-gerasimenko** [OmniSharp/omnisharp-emacs#378]
Hi,

I've tried to update to the latest version of plugin and install 1.24.0 server on Windows 10 with Emacs 25.3.1 but it fails, it seems like it tries to download from this URL which doesn't exist:
https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.24.0/omnisharp-win-x86-net46.zip

This one seems to work fine (after installing it manually):
https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.24.0/omnisharp-win-x86.zip

**Comment by razzmatazz** [comment]
oops, didn't see that urls for windows binaries have changed since on the server releases page.....

**Comment by razzmatazz** [comment]
should be good now, hopefully
