### ISSUE TITLE
Invalid function: helm-build-sync-source when starting server

### ISSUE THREAD

**Issue by LukeXuan** [OmniSharp/omnisharp-emacs#388]
As suggested, the error is reported when I execute `(omnisharp-start-omnisharp-server)`. It seems like this function is not autoloaded when the the lisp file is compiled.

**Comment by razzmatazz** [comment]
@LukeXuan are you using the latest omnisharp or the one from melpa.stable?

Because I think I have fixed this problem last week in commit https://github.com/OmniSharp/omnisharp-emacs/commit/e189a7f2d0de92af38a7970ce39e5adf8d1ae29b

**Comment by LukeXuan** [comment]
I'm using stable from melpa.

I'll have a try on the latest omnisharp.

**Comment by razzmatazz** [comment]
@LukeXuan btw, did it help?

**Comment by LukeXuan** [comment]
It works! Sorry I didn't post the update back. I hope we can see the fix reflected in melpa.stable :)

**Comment by razzmatazz** [comment]
Thanks! It should be there eventually :)
Just a couple of fixes to be done here https://github.com/OmniSharp/omnisharp-emacs/milestone/2

**Comment by razzmatazz** [comment]
Closing, as 4.2 release is looming
