### ISSUE TITLE
Windows: Invalid Function when installing the server

### ISSUE THREAD

**Issue by tluyben** [OmniSharp/omnisharp-emacs#390]
Windows 10
Emacs: 25.3
Spacemacs: installed + running
Powershell 5.1

M-x omnisharp-install-server gives me: 

omnisharp: attempting to download and install OmniSharp server into c:/Users/User/AppData/Roaming/.emacs.d/.cache/omnisharp/server/v1.24.0

omnisharp: extracting "omnisharp-win-x86.zip" into "c:/Users/User/AppData/Roaming/.emacs.d/.cache/omnisharp/server/v1.24.0"

helm-M-x: Invalid function: (let ((powershell-version (substring (shell-command-to-string "powershell -command \"(Get-Host).Version.Major\"") 0 -1))) (if (>= (string-to-number powershell-version) 5) (call-process "powershell" nil nil nil "-command" (concat "add-type -assembly system.io.compression.filesystem;" "[io.compression.zipfile]::ExtractToDirectory(\"" filename "\", \"" target-dir "\")")) (message (concat "omnisharp: for the 'M-x omnisharp-install-server' " " command to work on Windows you need to have powershell v5+ installed"))))

**Comment by razzmatazz** [comment]
Thanks for report @tluyben 
I think I fixed this issue in this PR: #396 — please reopen if that didn't fix your problem.

We just need to wait a bit for this change to get uploaded to melpa if you are using omnisharp-emacs off of it.
