### ISSUE TITLE
omnisharp-server: "System.NotSupportedException: Command '*' is not supported."

### ISSUE THREAD

**Issue by salvarubiomartinez** [OmniSharp/omnisharp-emacs#394]
I installed the CSharp layer on Spacemacs on Windows 10.
I took the binaris x64 for the omnisharp server.
For each request the server answer with a "System.NotSupportedException: Command '*' is not supported."
Output:
{"Request_seq":21,"Command":"typelookup","Running":true,"Success":false,"Message":"\"System.NotSupportedException: Command 'typelookup' is not supported.\\r\\n   en OmniSharp.Stdio.Host.<HandleRequest>d__14.MoveNext()\"","Body":null,"Seq":558,"Type":"response"}
{"Request_seq":22,"Command":"autocomplete","Running":true,"Success":false,"Message":"\"System.NotSupportedException: Command 'autocomplete' is not supported.\\r\\n   en OmniSharp.Stdio.Host.<HandleRequest>d__14.MoveNext()\"","Body":null,"Seq":559,"Type":"response"}

**Comment by razzmatazz** [comment]
Hi @salvarubiomartinez 
Are you using binaries from omnisharp-roslyn page (https://github.com/OmniSharp/omnisharp-roslyn/releases) or from the old server page (https://github.com/OmniSharp/omnisharp-server)? The old `omnisharp-server` binaries are not supported and you should always use `omnisharp-roslyn` ones.

Also, you may want to check installation docs for the `csharp` layer in the `develop` branch of spacemacs as documentation in `master` (stable/0.200) branch is out of date:
 - https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/csharp

There is also an issue with running x64 .NET binaries on Windows Emacs 2?.x—24.x, you may get more success with x86 one, unless you are running emacs 26.1+:
 - https://github.com/OmniSharp/omnisharp-emacs/issues/315

**Comment by salvarubiomartinez** [comment]
Thank you for your answer.
I took the roslyn binaries. I need C#6. I have Emacs  25.3.1.
I tried too with the x86 ones, but same result.
I will take a look at the documentation.

**Comment by razzmatazz** [comment]
Oops, I didn't write version numbers correctly, Emacs 25.x has the x64 .net crash issue as well. 26+ doesn't

Sure, please inform how it goes for you..

**Comment by salvarubiomartinez** [comment]
I did a fresh install of Spacemacs and it works perfectly well.
I thing the problem was that I first tried to build the omnisharp server and failed, and later I took the binaries. Probably some configuration was incoherent beacause of the crashed build.
This time I didn't try to build the omnisharp server and instead I used the binaries. And everything ok.
Great work

**Comment by razzmatazz** [comment]
Oh.. great it worked for you!

Closing this issue then..
