### ISSUE TITLE
Compilation fails on OSX using regular Emacs

### ISSUE THREAD

**Issue by Saikyun** [OmniSharp/omnisharp-emacs#401]
Using emacs 25.3.1, compilation of omnisharp fails. I have Mono through Unity. Do I need to install it separately?

In omnisharp--resolve-omnisharp-server-executable-path:  
omnisharp-server-management.el:53:9:Warning: reference to free variable  
    ‘omnisharp-server-executable-path’  
omnisharp-server-management.el:64:1:Error: Wrong type argument: listp, value  
Compiling file /Users/jona/.emacs.d/elpa/omnisharp-20171105.912/omnisharp-settings.el at Mon Nov 13 11:49:53 2017

**Comment by razzmatazz** [comment]
Hi @Saikyun 
I don't think it is related to mono version, rather than something to do with elisp code for omnisharp-emacs :(

Do you get these errors when installing or in runtime when starting the server via `M-x omnisharp-start-omnisharp-server`?

**Comment by razzmatazz** [comment]
Also, how do you perform installation, via init.el / (package-install xxxx) or interactively with `M-x package-list-packages`?

If you do it via init.el, there is an unresolved issue which might be related to your problem (which I didn't yet get to figuring out why that happens..):
  - https://github.com/OmniSharp/omnisharp-emacs/issues/369

**Comment by Saikyun** [comment]
Hi @razzmatazz 
I got the errors when installing using `M-x package-install`. I could not start the server, but I did however try the command `omnisharp-install-server`, and after doing that, the command `omnisharp-start-omnisharp-server` works, and I'm able to use commands such as `omnisharp-go-to-definition` (which is what I wanted the most).

**Comment by razzmatazz** [comment]
@Saikyun I think I have fixed the installation problem in #403 

Would you be able to confirm it works for you, i.e. uninstalling it and the installing it via `M-x package-install` again?

**Comment by Saikyun** [comment]
Works fine now! :) Thanks for a great package! Finally I can use emacs to
work on my unity projects! :) Cheers!

2017-11-16 8:12 GMT+01:00 Saulius Menkevičius <notifications@github.com>:

**Comment by razzmatazz** [comment]
great!
