### ISSUE TITLE
Emacs 26.09 on Windows - Omnisharp server 64 bits hangs Emacs

### ISSUE THREAD

**Issue by sebasmonia** [OmniSharp/omnisharp-emacs#402]
Related to issue #315, using the latests preview of Emacs with Omnisharp Server x64, after the server finishes initializing, Emacs will hang until you kill its process.
If I start the server from the console it loads fine,

Win7 64 bits. The solution file is a mix of netcore and framework 6.4 projects.

Thank you!

**Comment by razzmatazz** [comment]
Hi @sebasmonia 
Have you tried it with 25? Would be nice to know if it is omnisharp-emacs or emacs changes in 25 that trigger this. Also, as you know 25 does not support omnisharp server x64.. is there any particular reason you need x64 and not x86?

**Comment by sebasmonia** [comment]
Hi!
I will give it a try with 25 and see what happens. Actually I'm using the 26 pre-release because I read about existing problem with 25 in the issue referenced.

The solution builds 64 bits and if I try it with the x86 server, it fails to open with "Bad Image Exception". I tried changing the build configuration to use x86 but it wasn't working entirely right, eventually I gave up. 
Plus I work with others (who use VS) and at that point I might as well use VS myself rather than keep local changes just to accomodate my Emacs love :)

**Comment by razzmatazz** [comment]
Mhm, you might also want to try and build 25 with my patch applied too, if you are into that kidn of adventures :)

I think you will need to build emacs (25 or 26) with debugging symbols in order to get a stab where the hang is happening anyway..

**Comment by razzmatazz** [comment]
Btw, did you try to run the server manually with --stdio and -s flags from the terminal in order to check if x64 omnisharp-roslyn server actually helps you in any way?

Just run: `$path-to-server.exe --stdio -s <path-to-sln-file>` from your Windows shell/cmd.exe and the output should contain startup and project loading messages from the server in JSON format (although pretty readable by naked eyes)

**Comment by sebasmonia** [comment]
This is strange, I am running the latest version of the server and the --stdio option is not doing anything for me, apparently. I get "Omnisharp server running on port '2000' at location 'C:\HomeFolder\omnisharp_64' on host -1." 

Checking with omnisharp -h and "--stdio" doesn't appear listed. Maybe we are onto something here...

Also, I use Emacs at work, the target solution doesn't really belong to me. I have a "semi-locked" Windows environment. I think using Emacs is already a grey area :)
So I can't test the solution at home and I can't install the compile dependencies here. Sorry!

**Comment by sebasmonia** [comment]
¬_¬ I downloaded the HTTP version of the server, now they are separate downloads..............................

I'm testing now with the stdio version will update in a few minutes.

**Comment by sebasmonia** [comment]
OK, it works now. I still get no definitions and no usages for anything (which is what prompted me to try a newer version of the server and Emacs 26) but that's unrelated to this...errr...non issue.
