### ISSUE TITLE
Encoding problems?

### ISSUE THREAD

**Issue by simendsjo** [OmniSharp/omnisharp-emacs#412]
If I have some non-English type names, Omnisharp gives me errors. I've tried having the file as ISO-8859-1 and UTF-8 without any luck. I see the vscode integration starts the server with UTF-8 support, but I'm unable to find anything similar in the Emacs integration. https://github.com/OmniSharp/omnisharp-vscode/pull/726/commits/006f9d31e90834e15f1d00dc7a90d85e22213149

Is this something I can easily fix myself?

**Comment by razzmatazz** [comment]
@simendsjo sure, I think it should be simple to do

try inserting a line `"--encoding" "UTF-8"` before this line:
 - https://github.com/OmniSharp/omnisharp-emacs/blob/094b950baaee35a2b98fea129fa54f272e2499aa/omnisharp-server-management.el#L91

Please make a PR if this fixes the problem for you :)

**Comment by simendsjo** [comment]
Yes, that works. Wouldn't it be a sensible default?
I find it a bit strange that OmniSharp doesn't use the BOM correctly, but this might as well be a Roslyn issue for all I know.

**Comment by razzmatazz** [comment]
I think it would be a sensible value. And it is strange no one has encountered this before (or has not reported it otherwise).

Lets try to change the default to utf-8 and see if it doesn't break things for other people, as I am not 100% sure it is OK for everyone. Will introduce a customizable if this breaks things for some..

**Comment by simendsjo** [comment]
I doubt it will break for other people as it was already broken on my latin-1 files. But I know several other non-English projects use native language for domain words, but probably not that many Emacs users among them :)

**Comment by razzmatazz** [comment]
@simendsjo thanks! I merged the fix, should be in MELPA in a couple of hours
