### ISSUE TITLE
View all errors in solution

### ISSUE THREAD

**Issue by altschuler** [OmniSharp/omnisharp-emacs#414]
Is it possible to list all errors/warnings/issues in the solution? At the moment I'm relying on the compiler output (in this case Unity) to tell me if something is wrong in a file I'm not visiting.

**Comment by razzmatazz** [comment]
would be nice to have, definitely.. have you tried using vs code or atom editor in conjunction with omnisharp, do you know if they have it? – would be easy to implement then

i need to check it too

**Comment by razzmatazz** [comment]
yes, vs at least code has it in "Problems" view, we need to port it then..

**Comment by razzmatazz** [comment]
@altschuler ok, I have this new command `M-x omnisharp-solution-errors` which works about OK for me, could you check if it works for you too (once melpa has omnisharp-emacs uploaded in a couple of hours)?

**Comment by altschuler** [comment]
Fantastic! It works great! :)

It'd be very cool to be able to ignore warnings from certain files, as I currently see 430 issues of which I'm interested in ~10, so it's kind of hard to find them. Maybe this is possible through some general omnisharp config that I'm not aware of? 

Another cool feature would be to keep the buffer live updated somehow, either by polling or when saving, but that might be quite a costly task I suppose.

Thank you very much! This package is a life safer :)

**Comment by razzmatazz** [comment]
- Filtering is probably out of scope for this command as I would like to keep the thing small. You might want to check out `M-x helm-occur` or https://www.emacswiki.org/emacs/OccurMode, and probably there are even better solutions to filtering on buffer in emacs, I am somewhat a newbie too :)
 - Yeah, life update seems to be costly.. I have this solution where update takes 22 seconds. Not sure how atom or vscode omnisharp plugins go about this. Re-invoking `M-x omnisharp-solution-errors` manually should do the trick for now..

**Comment by razzmatazz** [comment]
Oh, and you can also pass universal parameter to make omnisharp-solution-errors to return actual errors only, sans warnings. `C-u M-x omnisharp-solution-errors` or `SPC u M-x omnisharp-solution-errors` on spacemacs.
