### ISSUE TITLE
Omnisharp-roslyn server returning empty responses

### ISSUE THREAD

**Issue by tushartyagi** [OmniSharp/omnisharp-emacs#424]
I'm using Omnisharp-4.2 on Debian 9 and I'm not able to get Autocomplete to work. I installed omnisharp-emacs using the install-prompt that comes up when opening the project.

I've followed the following steps to create a new dotnet project:

// In directory omnitest
`dotnet new console`
`dotnet new sln`

And running OmniSharp by passing it the `sln` file.

If I try to use autocomplete, the `OmniServer` buffer shows empty responses. Attaching the server-start log and autocomplete request log coming from the buffer.
[OmniServer-started.log](https://github.com/OmniSharp/omnisharp-emacs/files/1726362/OmniServer-started.log)
[Omnisharp-autocomplete-request.log](https://github.com/OmniSharp/omnisharp-emacs/files/1726364/Omnisharp-autocomplete-request.log)

Following is my setup:
Emacs 25.1
Omnisharp 4.2
Mono: 5.8
I'm using the emacs setup described at [Combined Setup Example](https://github.com/OmniSharp/omnisharp-emacs#combined-setup-example)

**Comment by razzmatazz** [comment]
Hi @tushartyagi 
Could you attach contents of `*omnisharp-log*` buffer in Emacs too?

**Comment by razzmatazz** [comment]
Also, did you try to invoke autocomplete functionality manually at some point in your .cs file by invoking `M-x company-autocomplete` – this should show a dropdown list of all the completions reported available from the omnisharp server at the point.

**Comment by tushartyagi** [comment]
@razzmatazz Here's the output of `*omnisharp-log*` buffer
[Omnisharp-log.log](https://github.com/OmniSharp/omnisharp-emacs/files/1728063/Omnisharp-log.log)

I don't have `company-autocomplete` function. There's a `company-complete` function but executing it prints `No completion found` in the minibuffer.

**Comment by razzmatazz** [comment]
I was wrong about `company-autocomplete` – `company-complete` is the one I suggested.

Apparently omnisharp server did not find any .csproj in your .sln file:
```
[09:17:39] INFORMATION: OmniSharp.MSBuild.MSBuildProjectSystem, Detecting projects in '/home/user/coding/dotnet/cs/omnitest/omnitest.sln'.
```

It should say this just after the line above if it finds any .csproj:
```
[17:43:21] INFORMATION: OmniSharp.MSBuild.MSBuildProjectSystem, Loading project: <path>
```

Can attach .sln file too? Btw, did you add .csproj to .sln file?

There is a fairly extensive documentation for `dotnet sln` subcommands at https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-sln.md

**Comment by tushartyagi** [comment]
Ah man! My bad. You're absolutely right. I did not add csproj to sln. :( 

Doing a `dotnet sln add omnitest.csproj` fixed it.

Sorry for taking your time. The autocomplete is working great now! Closing this issue. :)

**Comment by razzmatazz** [comment]
Great! no problem, nice that you got it working
