### ISSUE TITLE
 omnisharp-install-server errors out connecting to github

### ISSUE THREAD

**Issue by doomchild** [OmniSharp/omnisharp-emacs#429]
I'm getting the following output when I run `omnisharp-install-server`.  Any help would be greatly appreciated.

```
omnisharp: this will download and extract ~20-30 MB from "https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.26.3/omnisharp-osx.tar.gz"; do you want to continue? (y or n) y
omnisharp: attempting to download and install OmniSharp server into ~/.emacs.d/.cache/omnisharp/server/v1.26.3
omnisharp: downloading server binary from "https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.26.3/omnisharp-osx.tar.gz"...
Contacting host: github.com:443
Opening TLS connection to ‘github.com’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 github.com’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 github.com --protocols ssl3’...failed
Opening TLS connection to ‘github.com’...failed
url-http: Could not create connection to github.com:443
```

**Comment by razzmatazz** [comment]
Hi @doomchild 

This is on macOS, right? Which emacs version are you running? Do you have gnu-tls installed? This looks like emacs configuration issue if you can still access that github url from you browser.. https not working in your emacs? Could you try to visit, for example, https://www.google.com/ from eww browser in emacs?

If all fails, you can download the server file manually to some location and point to it with `omnisharp-server-executable-path` variable as detailed in this page:
 - https://github.com/OmniSharp/omnisharp-emacs/blob/master/doc/server-installation.md#manual-installation-on-macos-with-brew

I.e. you can manually download the file, no need to use brew on macos

**Comment by doomchild** [comment]
Yeah, this is on macOS.  I'm running version 26.0.50.  I don't think I have `gnu-tls` installed.  At any rate, I can't run `gnutls-cli` from a terminal.  Trying to hit https://www.google.com from `eww` gives me an error, so it definitely seems like it's a problem creating SSL connections from within emacs.

**Comment by doomchild** [comment]
Okay, it turns out I didn't have `gnutls` installed, and my emacs wasn't built with the `--with-gnutls` option.  Rebuilding it with that option (after installing `gnutls`) fixed things.  I'm closing this now.
