### ISSUE TITLE
Symbol's function definition is void: omnisharp-build-in-emacs

### ISSUE THREAD

**Issue by Bergiu** [OmniSharp/omnisharp-emacs#432]
Hi,

I am trying to run omnisharp-emacs with the following configuration:
omnisharp-20180121.702
Ubuntu 16.04.4 LTS
spacemacs

For the installation I wrote "csharp" into dotspacemacs-configuration-layers and restarted with `SPC feR`. Then I installed the server (v1.26.3) with `SPC SPC omnisharp-install-server` and restartet again. Then autocompletion works as expected. But omnisharp-code-format, -fix-usings, -auto-complete-overrides and -build-in-emacs doesn't work.

They return this error messages (depending on the called function):
`Symbol's function definition is void: omnisharp-build-in-emacs`
`Symbol's function definition is void: omnisharp-code-format`
and so on

After that I installed the omnisharp-roslyn (v1.29.1), like described [here](https://github.com/OmniSharp/omnisharp-emacs/blob/master/doc/server-installation.md), but it has the same results.

**Comment by razzmatazz** [comment]
which version of spacemacs are you using? 0.200.x or 0.300.x (develop) ?

the develop/0.300.x version has layer with updated settings.. 0.200.x has an outdated layer

**Comment by Bergiu** [comment]
Sorry, but I have uninstalled spacemacs and did't know the version that was installed. If you whish you can close the issue.

**Comment by razzmatazz** [comment]
ok.. sorry for not replying for so long.
