### ISSUE TITLE
Solution Files away from root directory

### ISSUE THREAD

**Issue by Kethku** [OmniSharp/omnisharp-emacs#460]
I work on a very large project with many csproj files. Building the entire solution at a time is not ideal for my use case as it takes way too long to build. To handle this in visual studio I created a user directory containing a specialized solution which references only the projects I need. Unfortunately this means that the custom solution file is not at the root of the project. Frustratingly Omnisharp disables itself if a given file is not in a subdirectory of the directory containing the solution file. 

This is broken. Solution files do not determine what files are included in their scope by which directory they are in. Its perfectly valid to have a solution file that references csproj files located anywhere in the file system.

Interestingly enough if I restart the omnisharp server specifying the particular solution file while keeping the csharp files open then completion works perfectly.

**Comment by razzmatazz** [comment]
@Kethku I believe this has been fixed with the latest version as it now attempts to figure out the root of the project from SCM/git/projectile (i.e. does not require for .sln file to be specified–works like vscode where you don't need to specify a .sln file)

**Comment by razzmatazz** [comment]
@Kethku closing, please reopen if this actually has not been fixed..
