### ISSUE TITLE
Selecting a solution file requires the solution to be in a parent directory of a given csharp file

### ISSUE THREAD

**Issue by Kethku** [OmniSharp/omnisharp-emacs#461]
If I have a csharp file open in emacs in some location and want to start an omnisharp server instance for the solution that contains this file, the only solutions I have access to are the ones that are contained by a parent directory of said csharp file.

Ex:
```
foo/
    solution1.sln
    bar/
        solution2.sln
    baz/
        csharpFile.cs
```
In the above folder structure, if I open csharpFile.cs and call omnisharp-start-omnisharp-server the only solution file I am able to select is solution1.sln. solution2.sln is not in the list regardless of whether or not it contains csharpFile.cs

To get around this issue I open a file in the directory containing the solution I want to start the omnisharp server for (possibly even the solution itself) and call omnisharp-start-omnisharp-server from their instead which suggests both solution1.sln and solution2.sln as possibilities. This is cumbersome and unnecessary as solution1.sln and solution2.sln are both valid options for starting an omnisharp sever.

**Comment by razzmatazz** [comment]
Thanks for the report. I will look into it. One of the issues (IIRC) is that omnisharp will consider subdirectory tree down the directory where the loaded .sln resides as the only valid subdir tree where .cs files are considered to be valid.

So I am not sure at the moment if there is a quick solution for this problem considering current assumptions in the code..

**Comment by razzmatazz** [comment]
@Kethku I have released an updated version of omnisharp-emacs which no longer uses .sln files for discovering project root but tries to figure it from SCM/.git/projectile-root.

Could you check if that fixes this issue for you?

**Comment by bezirg** [comment]
If `projectile` is not installed, it will not automatically start `omnisharp-server`. I am not a user of `projectile`, but I installed it and added an empty `.projectile` , on project root and I confirm that `omnisharp-emacs` picks up the path and automatically starts the server.

**Comment by razzmatazz** [comment]
@Kethku closing this issue, please reopen if it is still not fixed
