### ISSUE TITLE
Shut-up is preventing omnisharp from loading

### ISSUE THREAD

**Issue by brettgilio** [OmniSharp/omnisharp-emacs#462]
Hi there. I am using the 10-23-2018 version of Omnisharp from MELPA. I am getting an error whenever I try to start the omnisharp server that shut-up is an invalid function. I can confirm that shut-up is loaded in emacs, and that I am not doing anything outside of what is recommended for Omnisharp as the configuration is standard. I can also confirm from list-processes that Omnisharp is not started, and the omnisharp-log is not producing anything that suggests an error. It makes me think that maybe this is an issue with shut-up, but that package has not been updated in years so I can not reasonably see why that would affect omnisharp as it has been working up til now.

Emacs 26.1

**Comment by razzmatazz** [comment]
Btw, did this broke at some point or it never worked for you?

**Comment by razzmatazz** [comment]
I have introduce some changes in #463 which I will merge shortly which remove dependency on `shut-up`. The changes should be released tommorow automatically by melpa.org – hopefully this will fix your issue.

**Comment by razzmatazz** [comment]
I am closing this issue as my changes that remove dependency on shut-up are in for a long time (but might not be in melpa-stable as that requires a tagged "stable" release).
Please reopen if this still occurs.
