### ISSUE TITLE
Guix - omnisharp server terminated

### ISSUE THREAD

**Issue by Robin-Wils** [OmniSharp/omnisharp-emacs#469]
The guix package manager saves packages on an unregular location. 

Is there a way to change the path of the server?  
I think that this is a guix-only problem.
I can use vscode for now but I prefer emacs.

**Comment by razzmatazz** [comment]
Do you want to change the path where omnisharp-emacs installs the server binary (on $HOME/.emacs.d/cache/omnisharp usually) or do you want to download server binary manually and set the path to it so omnisharp-emacs would use it?

For the later case you can:
```elisp
(setq omnisharp-server-executable-path "your/path/to/binary")
```

in your init.el

**Comment by Robin-Wils** [comment]
Hmmm, it is apparently installed on the correct path, my bad.
Guix saves some packages under another location, but this one is stored in the regular location.
  
I receive "omnisharp: server has been terminated" in the minibuffer.
Omnisharp works fine in vscode.
My config contains the Combined setup example from the README.

**Comment by razzmatazz** [comment]
Have you checked the `*omnisharp-emacs*` buffer for any log messages from the server?

**Comment by Robin-Wils** [comment]
Thanks for the reply.  

I think that I already see the issue. I selected a ".csproj" file.
I don't use ".sln" files. I use it for dotnet core.  
(currently a new empty web project)

This could mean that I have to use vscode for now (which is fine).
[omnisharp log](https://privatebin.net/?abf0fbc5d94aa5d3#NMPS1AqXNBn0nZnx96T6XhJjdlecoahO1Qu0H4J3lyU=)

**Comment by razzmatazz** [comment]
You can actually create .sln file with the dotnet tool:
```
 $ dotnet new sln  <-- creates sln file with the name of the parent directory
 $ dotnet sln solution.sln add path/to/project.csproj
```

But yes, this is a current limitation of `omnisharp-emacs`, we should fix this.

**Comment by Robin-Wils** [comment]
Wow, thanks a lot!  

The IntelliSense works now, it is pretty cool.  
This is exactly what I wanted.
I would suggest the team to add those sln instructions to the README.
