### ISSUE TITLE
razorfile & cshtml file support

### ISSUE THREAD

**Issue by chayward1** [OmniSharp/omnisharp-emacs#503]
Editor: Doom Emacs v2.0.9

Hello! Sorry if this is not the right place to ask this but I am curious about if there is the option of syntax highlighting for both razorfiles (.razor) and cshtml files?

**Comment by razzmatazz** [comment]
Hi @chayward1. No, razor file "intellisense" is not supported with omnisharp-emacs. We're thinking about deprecating this project when (once) we have LSP servers available that support C# properly.
 - See https://github.com/OmniSharp/omnisharp-emacs/issues/500

Most probably, LSP server needs to be written for razor OR integrated into existing C# servers.
