### ISSUE TITLE
Omnisharp requires external projectile when built-in (>25.1) project.el would do the job as well

### ISSUE THREAD

**Issue by pcrama** [OmniSharp/omnisharp-emacs#511]
I do not have projectile installed, but since Emacs 25.1, Emacs ships with a built-in project.el library and I use that instead.

I made this the fall back option because if a user went to the trouble of installing a 3rd party library (projectile), he/she probably prefers it over the built-in solution.

See PR #508.

**Comment by razzmatazz** [comment]
This has been merged (albeit with a long delay -- sorry). @pcrama
