### ISSUE TITLE
no autocomplete without explicitly typing "company-complete"?

### ISSUE THREAD

**Issue by matejsarlija** [OmniSharp/omnisharp-emacs#513]
Hi, was just wondering what is the key to trigger autocomplete directly in emacs, for now I only get complete if I explicitly type "company-complete" via M-x, or clicking complete at point under Omnisharp tab?

I'm a noob, thank you.

**Comment by razzmatazz** [comment]
Hi @matejsarlija 

Just typing . (dot) after type/variable name should work, should the context provide anything to autocomplete. Have you tried configuring the mode properly with:
 - https://github.com/OmniSharp/omnisharp-emacs#combined-setup-example

Are you using some specific emacs bundle (doom/spacemacs?)

Also I would strongly suggest trying lsp-mode (or eglot) as that is the way forward for C# IDE features in emacs, unless you depend on omnisharp-emacs specific features (unit testing, type inspection from assemblies) -- which have not been ported to lsp-mode yet.

**Comment by matejsarlija** [comment]
Hi @razzmatazz , thanks, I've tried adding the combined setup to both .emacs and init.el, didn't see a change. I'll try lsp-mode. I *am* running vanilla emacs, but it is through Chocolatey on windows so that may have some impact.

**Comment by dennissherb** [comment]
Why was this closed? this issue still persists for me on doom and it's specific to company-omnisharp...
