### ISSUE TITLE
Issues on the natively compiled brach with dash macro

### ISSUE THREAD

**Issue by dakling** [OmniSharp/omnisharp-emacs#515]
Hi,

when natively compiling `omnisharp-emacs`, after invoking `omnisharp-start-omnisharp-server`, I get the error 
`(void-variable it)`. The issue probably lies in the macroexpansion of dash's `--map`-macro in `omnisharp-server-management.el`.

Since this only occurs when using native compilation, I also considered reporting a bug there, however, as far as I can tell, other packages using `--map` do not have this issue. Not sure why, but according to [this ancient issue](https://github.com/magnars/dash.el/issues/7), which discusses the same error in the context of byte-compilation, it might be good practice to include `(require 'dash)` in every file of the package that uses `--map` (I wasn't able to test if this works in this case yet). I am only speculating, though - what do you think?

Of course, since the `--map`-macro is used only once, a crude but simple solution could also be to just replace it with the non-macro version `-map`. Would you accept a PR along these lines?

Best,

Dario

**Comment by razzmatazz** [comment]
Hi @dakling -- definitely make a PR, we will take it :)

Right, we've had some issues with autoload'ed files before.
