### ISSUE TITLE
Warn user if the expected backend version is not running

### ISSUE THREAD

**Issue by sp3ctum** [OmniSharp/omnisharp-emacs#73]
Here's my idea of a use case:
- user edits a .cs file and uses omnisharp-emacs
- user has an OmnisharpServer instance running in the background
- omnisharp-emacs expects OmnisharpServer to be of version `foo`
- OmnisharpServer is of version `bar`
- something weird happens. Perhaps the user gets no auto-completions.
- user runs a function that checks that OmnisharpServer is running and
  has the expected version.
- omnisharp-emacs gives a warning to the user about mismatched versions.

**Comment by razzmatazz** [comment]
I think we have this resolved this with the new `M-x omnisharp-install-server` command which will use `(defcustom omnisharp-expected-server-version ...)` and will ask to install new server version when omnisharp-emacs is updated.

Closing
