### ISSUE TITLE
Using formatting style from OmniSharp

### ISSUE THREAD

**Issue by d12frosted** [OmniSharp/omnisharp-emacs#95]
Hello. I was using OmniSharp-emacs and found this uncomfortable behaviour after changing OmniSharp formatting settings. When you use `omnisharp-code-format` everything looks as you customised. But when you type code it gets formatted with different style. And it really confuses me. Is it possible to use formatting style from OmniSharp? 

Please, look at attached screenshot. 

![screenshot 2014-07-16 17 30 06](https://cloud.githubusercontent.com/assets/6507913/3600172/ea4db44e-0cf5-11e4-87b6-784d6e5555cb.png)

P. S. I am using GNU Emacs 24.3.1. I have installed only `omnisharp-emacs`, `csharp-mode` and `company` for editing `C#` sources.

**Comment by jojojames** [comment]
@d12frosted Could you explain how you solved your problem?

**Comment by d12frosted** [comment]
@jojojames properly setting up indentation in emacs solved my problem. In order to do so you have to play with play with either `c-default-style` or configure every indentation bit by yourself. See `c-set-style`, `c-set-offset` and `c-offsets-alist`. The latter variable's documentation contains many useful information on what you can configure 😸 [IndentingC](http://www.emacswiki.org/emacs/IndentingC#toc11) contains several examples.
